using LagerthaAssistant.Application.Constants;
using LagerthaAssistant.Application.Interfaces;
using Microsoft.Extensions.Logging;

namespace LagerthaAssistant.Infrastructure.Services;

public sealed class LocalizationService : ILocalizationService
{
    private readonly ILogger<LocalizationService>? _logger;

    public LocalizationService(ILogger<LocalizationService>? logger = null)
    {
        _logger = logger;
    }

    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["menu.main.title"] = "What can I help you with?",
        ["menu.main.chat"] = "🗣 Chat",
        ["menu.main.vocabulary"] = "📚 Vocabulary",
        ["menu.main.shopping"] = "🛒 Shopping",
        ["menu.main.menu"] = "🍽 Menu",
        ["menu.main.settings"] = "⚙️ Settings",
        ["menu.vocabulary.title"] = "📚 Vocabulary\n\nYou have {0} words. What shall we do?",
        ["menu.vocabulary.add"] = "➕ Add word",
        ["menu.vocabulary.list"] = "📋 My list",
        ["menu.vocabulary.url"] = "🔗 From URL",
        ["menu.vocabulary.batch"] = "📦 Batch mode",
        ["menu.vocabulary.back"] = "🔙 Main menu",
        ["menu.shopping.title"] = "🛒 Shopping",
        ["menu.shopping.add"] = "➕ Add item",
        ["menu.shopping.list"] = "📋 View list",
        ["menu.shopping.delete"] = "🗑 Remove item",
        ["menu.shopping.back"] = "🔙 Main menu",
        ["menu.weekly.title"] = "🍽 Weekly Menu",
        ["menu.weekly.view"] = "📅 View menu",
        ["menu.weekly.plan"] = "🤖 Plan with AI",
        ["menu.weekly.calories"] = "📊 Calories",
        ["menu.weekly.back"] = "🔙 Main menu",
        ["stub.wip"] = "🚧 This feature is under development. Coming soon!",
        ["start.welcome"] = "👋 Hi! I'm Lagertha — your personal assistant.\n\nI can help you:\n📚 Learn English words\n🛒 Keep a shopping list\n🍽 Plan your weekly menu\n🗣 Chat and help with anything\n\nChoose a section or just write to me!",
        ["locale.switched"] = "🌐 Language set to English",
        ["vocab.add.prompt"] = "Send me a word or phrase in English and I'll look it up for you.",
        ["vocab.url.prompt"] = "Send me a URL to an article and I'll extract new words for you.",
        ["vocab.batch.prompt"] = "Send several words or phrases in one message (new lines, commas, semicolons, or sentences), and I will process them in batch mode.",
        ["vocab.list.empty"] = "Your vocabulary list is empty.",
        ["vocab.list.title"] = "📋 Your latest words:",
        ["onboarding.choose_language"] = "👋 Welcome!\n\nPlease choose your language:",
        ["onboarding.language_saved"] = "🎉 Great! Language saved.\n\nHi! I'm Lagertha — your personal assistant. How can I help?",
        ["settings.title"] = "⚙️ <b>Settings</b>",
        ["settings.language"] = "🌐 Language",
        ["settings.save_mode"] = "💾 Save mode",
        ["settings.storage_mode"] = "💽 Storage mode",
        ["settings.onedrive"] = "☁️ OneDrive / Graph",
        ["settings.notion"] = "📝 Notion (coming soon)",
        ["settings.back"] = "🔙 Main menu",
        ["settings.change_language"] = "🌐 Change language",
        ["settings.change_save_mode"] = "💾 Change save mode",
        ["settings.change_storage_mode"] = "💽 Change storage mode",
        ["language.current"] = "🌐 <b>Language</b>\n\nCurrent: {0}\n\nChoose new language:",
        ["language.changed"] = "✅ Language changed to {0}",
        ["savemode.title"] = "💾 <b>Save mode</b>\n\nCurrent: <b>{0}</b>\n\n• <b>auto</b> — save words automatically\n• <b>ask</b> — confirm before each save\n• <b>off</b> — don't save to deck",
        ["savemode.changed"] = "✅ Save mode changed to <b>{0}</b>",
        ["savemode.auto"] = "💾 auto",
        ["savemode.ask"] = "❓ ask",
        ["savemode.off"] = "🚫 off",
        ["storagemode.title"] = "💽 <b>Storage mode</b>\n\nCurrent: <b>{0}</b>\n\n• <b>local</b> — save to local Excel files\n• <b>graph</b> — save to OneDrive via Microsoft Graph",
        ["storagemode.changed"] = "✅ Storage mode changed to <b>{0}</b>",
        ["storagemode.local"] = "💾 local",
        ["storagemode.graph"] = "☁️ graph",
        ["vocab.save.ask"] = "Save \"{0}\" to \"{1}\"?",
        ["vocab.save.saved"] = "✅ Saved to {0} (row {1}).",
        ["vocab.save.duplicate"] = "ℹ️ Word already exists in writable decks. Save skipped.",
        ["vocab.save.skip"] = "ℹ️ Save skipped.",
        ["vocab.save_failed"] = "⚠️ Save failed: {0}",
        ["vocab.save_batch_ask_hint"] = "Save mode is ask. For batch auto-save, switch save mode to auto.",
        ["vocab.save_mode_off_hint"] = "Save mode is off. Switch it to ask or auto in Settings.",
        ["vocab.save_yes"] = "✅ Save",
        ["vocab.save_no"] = "❌ Skip",
        ["vocab.no_pending_save"] = "No pending save request.",
        ["vocab.word_unrecognized"] = "⚠️ Word \"{0}\" is not recognized. Send a corrected English word.",
        ["vocab.word_unrecognized_with_suggestions"] = "⚠️ Word \"{0}\" is not recognized. Did you mean: {1}? Send the corrected word.",
        ["vocab.found_in_deck_single"] = "ℹ️ Word already exists in dictionary: {0} (row {1}).",
        ["vocab.found_in_deck_multi_title"] = "ℹ️ These words already exist in dictionary:",
        ["vocab.found_in_deck_multi_item"] = "• {0}: {1} (row {2})",
        ["vocab.graph_save_setup_required"] = "To save words, open Settings -> OneDrive / Graph, sign in, and try again.",
        ["command.console_only_generic"] = "⚠️ The {0} command is available only in the console app. In Telegram, use menu buttons or natural language.",
        ["command.console_only_graph"] = "⚠️ The {0} command is console-only. To save words in Telegram, open Settings -> OneDrive / Graph and sign in.",
        ["onedrive.login_switched_to_graph"] = "✅ OneDrive connected. Storage mode switched to <b>graph</b>.",
        ["onedrive.title"] = "☁️ <b>OneDrive / Graph</b>",
        ["onedrive.status_connected"] = "Status: ✅ Connected",
        ["onedrive.status_disconnected"] = "Status: ❌ Not connected",
        ["onedrive.error_not_authenticated"] = "OneDrive authorization is required. Open Settings -> OneDrive / Graph and sign in.",
        ["onedrive.error_expired"] = "OneDrive session expired. Open Settings -> OneDrive / Graph and sign in again.",
        ["onedrive.error_not_configured"] = "Graph integration is not configured on the server.",
        ["onedrive.error_timed_out"] = "Login timed out. Try sign-in again from Settings -> OneDrive / Graph.",
        ["onedrive.error_declined"] = "Login was declined. Try sign-in again from Settings -> OneDrive / Graph.",
        ["onedrive.login"] = "🔑 Sign in to OneDrive",
        ["onedrive.logout"] = "🚪 Sign out",
        ["onedrive.login_started"] = "🔑 To sign in, open this link and enter the code:\n\n<b>{0}</b>\n\nLink: {1}\n\nCode expires in {2} minutes.",
        ["onedrive.logout_done"] = "✅ Signed out from OneDrive.",
        ["onedrive.check_status"] = "✅ I've signed in",
        ["onedrive.still_not_signed_in"] = "Still not signed in. Try again?",
        ["onedrive.sync_now"] = "🔄 Sync pending saves",
        ["onedrive.rebuild_index"] = "🧱 Rebuild index",
        ["onedrive.rebuild_index_warning"] = "⚠️ Rebuilding index can take some time on large decks. Start now?",
        ["onedrive.rebuild_index_start"] = "✅ Start rebuild",
        ["onedrive.rebuild_index_started"] = "⏳ Rebuilding index. This may take a few minutes...",
        ["onedrive.rebuild_index_suggest"] = "💡 Tip: index appears empty. Tap “Rebuild index” to import existing words from OneDrive decks.",
        ["onedrive.index_ready"] = "✅ Index is already up to date: {0} words in your dictionary.",
        ["onedrive.sync_now_done"] = "✅ Sync complete: completed={0}, requeued={1}, failed={2}, pending={3}.",
        ["onedrive.rebuild_index_done"] = "✅ Index rebuilt from writable decks: scanned={0}, indexed={1}.",
        ["onedrive.operation_failed"] = "⚠️ Operation failed: {0}",
        ["notion.title"] = "📝 <b>Notion</b>\n\n🚧 This integration is under development. Coming soon!",
        ["back"] = "🔙 Back",
        ["language.name.uk"] = "🇺🇦 Українська",
        ["language.name.en"] = "🇬🇧 English",
        ["language.name.es"] = "🇪🇸 Español",
        ["language.name.fr"] = "🇫🇷 Français",
        ["language.name.de"] = "🇩🇪 Deutsch",
        ["language.name.pl"] = "🇵🇱 Polski",
        ["language.name.de_pl"] = "🇩🇪 Deutsch · 🇵🇱 Polski"
    };

    private static readonly IReadOnlyDictionary<string, string> Ukrainian = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["menu.main.title"] = "Чим можу допомогти?",
        ["menu.main.chat"] = "🗣 Чат",
        ["menu.main.vocabulary"] = "📚 Словник",
        ["menu.main.shopping"] = "🛒 Покупки",
        ["menu.main.menu"] = "🍽 Меню",
        ["menu.main.settings"] = "⚙️ Налаштування",
        ["menu.vocabulary.title"] = "📚 Словник\n\nУ тебе {0} слів. Що зробимо?",
        ["menu.vocabulary.add"] = "➕ Додати слово",
        ["menu.vocabulary.list"] = "📋 Мій список",
        ["menu.vocabulary.url"] = "🔗 З посилання",
        ["menu.vocabulary.batch"] = "📦 Batch режим",
        ["menu.vocabulary.back"] = "🔙 Головне меню",
        ["menu.shopping.title"] = "🛒 Покупки",
        ["menu.shopping.add"] = "➕ Додати товар",
        ["menu.shopping.list"] = "📋 Список",
        ["menu.shopping.delete"] = "🗑 Видалити товар",
        ["menu.shopping.back"] = "🔙 Головне меню",
        ["menu.weekly.title"] = "🍽 Меню на тиждень",
        ["menu.weekly.view"] = "📅 Переглянути меню",
        ["menu.weekly.plan"] = "🤖 Запропонуй меню",
        ["menu.weekly.calories"] = "📊 Калорії",
        ["menu.weekly.back"] = "🔙 Головне меню",
        ["stub.wip"] = "🚧 Ця функція в розробці. Скоро буде!",
        ["start.welcome"] = "👋 Привіт! Я Lagertha — твій особистий асистент.\n\nЯ вмію:\n📚 Вивчати англійські слова\n🛒 Вести список покупок\n🍽 Планувати меню на тиждень\n🗣 Просто розмовляти та допомагати\n\nОбери розділ або просто напиши мені!",
        ["locale.switched"] = "🌐 Мову змінено на українську",
        ["vocab.add.prompt"] = "Надішли слово або фразу англійською, і я знайду її для тебе.",
        ["vocab.url.prompt"] = "Надішли посилання на статтю, і я витягну нові слова.",
        ["vocab.batch.prompt"] = "Надішли кілька слів або фраз одним повідомленням (новими рядками, комами, крапкою з комою або реченнями), і я оброблю їх у batch режимі.",
        ["vocab.list.empty"] = "Твій список слів поки порожній.",
        ["vocab.list.title"] = "📋 Останні слова:",
        ["onboarding.choose_language"] = "👋 Вітаємо!\n\nБудь ласка, оберіть мову:",
        ["onboarding.language_saved"] = "🎉 Чудово! Мову збережено.\n\nПривіт! Я Lagertha — твій особистий асистент. Чим можу допомогти?",
        ["settings.title"] = "⚙️ <b>Налаштування</b>",
        ["settings.language"] = "🌐 Мова",
        ["settings.save_mode"] = "💾 Режим збереження",
        ["settings.storage_mode"] = "💽 Режим сховища",
        ["settings.onedrive"] = "☁️ OneDrive / Graph",
        ["settings.notion"] = "📝 Notion (скоро)",
        ["settings.back"] = "🔙 Головне меню",
        ["settings.change_language"] = "🌐 Змінити мову",
        ["settings.change_save_mode"] = "💾 Змінити режим збереження",
        ["settings.change_storage_mode"] = "💽 Змінити режим сховища",
        ["language.current"] = "🌐 <b>Мова</b>\n\nПоточна: {0}\n\nОберіть нову мову:",
        ["language.changed"] = "✅ Мову змінено на {0}",
        ["savemode.title"] = "💾 <b>Режим збереження</b>\n\nПоточний: <b>{0}</b>\n\n• <b>auto</b> — зберігати автоматично\n• <b>ask</b> — підтверджувати перед збереженням\n• <b>off</b> — не зберігати в деку",
        ["savemode.changed"] = "✅ Режим збереження змінено на <b>{0}</b>",
        ["savemode.auto"] = "💾 auto",
        ["savemode.ask"] = "❓ ask",
        ["savemode.off"] = "🚫 off",
        ["storagemode.title"] = "💽 <b>Режим сховища</b>\n\nПоточний: <b>{0}</b>\n\n• <b>local</b> — збереження в локальні Excel-файли\n• <b>graph</b> — збереження в OneDrive через Microsoft Graph",
        ["storagemode.changed"] = "✅ Режим сховища змінено на <b>{0}</b>",
        ["storagemode.local"] = "💾 local",
        ["storagemode.graph"] = "☁️ graph",
        ["vocab.save.ask"] = "Зберегти \"{0}\" у \"{1}\"?",
        ["vocab.save.saved"] = "✅ Збережено в {0} (рядок {1}).",
        ["vocab.save.duplicate"] = "ℹ️ Слово вже є у writable-деках. Збереження пропущено.",
        ["vocab.save.skip"] = "ℹ️ Збереження пропущено.",
        ["vocab.save_failed"] = "⚠️ Помилка збереження: {0}",
        ["vocab.save_batch_ask_hint"] = "Режим збереження ask. Для batch-автозбереження перемкни на auto.",
        ["vocab.save_mode_off_hint"] = "Режим збереження off. Перемкни в Settings на ask або auto.",
        ["vocab.save_yes"] = "✅ Зберегти",
        ["vocab.save_no"] = "❌ Пропустити",
        ["vocab.no_pending_save"] = "Немає запиту на збереження.",
        ["vocab.word_unrecognized"] = "⚠️ Слово \"{0}\" не розпізнано. Надішли виправлений англійський варіант.",
        ["vocab.word_unrecognized_with_suggestions"] = "⚠️ Слово \"{0}\" не розпізнано. Можливо, ти мав на увазі: {1}? Надішли виправлене слово.",
        ["vocab.found_in_deck_single"] = "ℹ️ Слово вже є у словнику: {0} (рядок {1}).",
        ["vocab.found_in_deck_multi_title"] = "ℹ️ Ці слова вже є у словнику:",
        ["vocab.found_in_deck_multi_item"] = "• {0}: {1} (рядок {2})",
        ["vocab.graph_save_setup_required"] = "Щоб зберігати слова, відкрий Налаштування -> OneDrive / Graph, увійди і спробуй ще раз.",
        ["command.console_only_generic"] = "⚠️ Команда {0} доступна лише в консольному застосунку. У Telegram використовуй кнопки меню або природну мову.",
        ["command.console_only_graph"] = "⚠️ Команда {0} доступна лише в консолі. Щоб зберігати слова в Telegram, відкрий Налаштування -> OneDrive / Graph і увійди.",
        ["onedrive.login_switched_to_graph"] = "✅ OneDrive підключено. Режим сховища перемкнено на <b>graph</b>.",
        ["onedrive.title"] = "☁️ <b>OneDrive / Graph</b>",
        ["onedrive.status_connected"] = "Статус: ✅ Підключено",
        ["onedrive.status_disconnected"] = "Статус: ❌ Не підключено",
        ["onedrive.error_not_authenticated"] = "Потрібна авторизація OneDrive. Відкрий Налаштування -> OneDrive / Graph і увійди.",
        ["onedrive.error_expired"] = "Сесія OneDrive завершилась. Відкрий Налаштування -> OneDrive / Graph і увійди знову.",
        ["onedrive.error_not_configured"] = "Graph інтеграція не налаштована на сервері.",
        ["onedrive.error_timed_out"] = "Час входу вийшов. Спробуй ще раз у Налаштування -> OneDrive / Graph.",
        ["onedrive.error_declined"] = "Вхід було відхилено. Спробуй ще раз у Налаштування -> OneDrive / Graph.",
        ["onedrive.login"] = "🔑 Увійти в OneDrive",
        ["onedrive.logout"] = "🚪 Вийти",
        ["onedrive.login_started"] = "🔑 Щоб увійти, відкрий посилання та введи код:\n\n<b>{0}</b>\n\nПосилання: {1}\n\nКод діє {2} хвилин.",
        ["onedrive.logout_done"] = "✅ Вихід з OneDrive виконано.",
        ["onedrive.check_status"] = "✅ Я вже увійшов",
        ["onedrive.still_not_signed_in"] = "Ще не авторизовано. Спробувати ще раз?",
        ["onedrive.sync_now"] = "🔄 Синхронізувати чергу",
        ["onedrive.rebuild_index"] = "🧱 Перезібрати індекс",
        ["onedrive.rebuild_index_warning"] = "⚠️ Перезбір індексу може зайняти деякий час на великих деках. Запустити зараз?",
        ["onedrive.rebuild_index_start"] = "✅ Запустити перезбір",
        ["onedrive.rebuild_index_started"] = "⏳ Перезбираю індекс. Це може тривати кілька хвилин...",
        ["onedrive.rebuild_index_suggest"] = "💡 Порада: індекс виглядає порожнім. Натисни «Перезібрати індекс», щоб імпортувати наявні слова з OneDrive-дек.",
        ["onedrive.index_ready"] = "✅ Індекс уже в порядку: у словнику {0} слів.",
        ["onedrive.sync_now_done"] = "✅ Синхронізацію завершено: виконано={0}, повторно в чергу={1}, помилок={2}, в черзі={3}.",
        ["onedrive.rebuild_index_done"] = "✅ Індекс перезібрано з writable-дек: перевірено={0}, проіндексовано={1}.",
        ["onedrive.operation_failed"] = "⚠️ Операція не вдалася: {0}",
        ["notion.title"] = "📝 <b>Notion</b>\n\n🚧 Ця інтеграція в розробці. Скоро буде!",
        ["back"] = "🔙 Назад",
        ["language.name.uk"] = "🇺🇦 Українська",
        ["language.name.en"] = "🇬🇧 English",
        ["language.name.es"] = "🇪🇸 Español",
        ["language.name.fr"] = "🇫🇷 Français",
        ["language.name.de"] = "🇩🇪 Deutsch",
        ["language.name.pl"] = "🇵🇱 Polski",
        ["language.name.de_pl"] = "🇩🇪 Deutsch · 🇵🇱 Polski"
    };

    private static readonly IReadOnlyDictionary<string, string> Spanish = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["menu.main.title"] = "¿Cómo puedo ayudarte?",
        ["menu.main.chat"] = "🗣 Chat",
        ["menu.main.vocabulary"] = "📚 Vocabulario",
        ["menu.main.shopping"] = "🛒 Compras",
        ["menu.main.menu"] = "🍽 Menú",
        ["menu.main.settings"] = "⚙️ Ajustes",
        ["menu.vocabulary.title"] = "📚 Vocabulario\n\nTienes {0} palabras. ¿Qué hacemos?",
        ["menu.vocabulary.add"] = "➕ Añadir palabra",
        ["menu.vocabulary.list"] = "📋 Mi lista",
        ["menu.vocabulary.url"] = "🔗 Desde URL",
        ["menu.vocabulary.batch"] = "📦 Modo batch",
        ["menu.vocabulary.back"] = "🔙 Menú principal",
        ["menu.shopping.title"] = "🛒 Compras",
        ["menu.shopping.add"] = "➕ Añadir artículo",
        ["menu.shopping.list"] = "📋 Ver lista",
        ["menu.shopping.delete"] = "🗑 Eliminar artículo",
        ["menu.shopping.back"] = "🔙 Menú principal",
        ["menu.weekly.title"] = "🍽 Menú semanal",
        ["menu.weekly.view"] = "📅 Ver menú",
        ["menu.weekly.plan"] = "🤖 Planificar con IA",
        ["menu.weekly.calories"] = "📊 Calorías",
        ["menu.weekly.back"] = "🔙 Menú principal",
        ["stub.wip"] = "🚧 Esta función está en desarrollo. ¡Próximamente!",
        ["start.welcome"] = "👋 ¡Hola! Soy Lagertha — tu asistente personal.\n\nPuedo ayudarte a:\n📚 aprender palabras en inglés\n🛒 llevar una lista de compras\n🍽 planificar tu menú semanal\n🗣 chatear y ayudarte con cualquier cosa\n\n¡Elige una sección o escríbeme directamente!",
        ["locale.switched"] = "🌐 Idioma cambiado a español",
        ["vocab.add.prompt"] = "Envíame una palabra o frase en inglés y la buscaré para ti.",
        ["vocab.url.prompt"] = "Envíame la URL de un artículo y extraeré palabras nuevas para ti.",
        ["vocab.batch.prompt"] = "Envía varias palabras o frases en un solo mensaje (líneas nuevas, comas, punto y coma o frases) y las procesaré en modo batch.",
        ["vocab.list.empty"] = "Tu lista de vocabulario está vacía.",
        ["vocab.list.title"] = "📋 Tus últimas palabras:",
        ["onboarding.choose_language"] = "👋 ¡Bienvenido!\n\nElige tu idioma:",
        ["onboarding.language_saved"] = "🎉 ¡Genial! Idioma guardado.\n\n¡Hola! Soy Lagertha — tu asistente personal. ¿Cómo puedo ayudarte?",
        ["settings.title"] = "⚙️ <b>Ajustes</b>",
        ["settings.language"] = "🌐 Idioma",
        ["settings.save_mode"] = "💾 Modo de guardado",
        ["settings.storage_mode"] = "💽 Modo de almacenamiento",
        ["settings.onedrive"] = "☁️ OneDrive / Graph",
        ["settings.notion"] = "📝 Notion (próximamente)",
        ["settings.back"] = "🔙 Menú principal",
        ["settings.change_language"] = "🌐 Cambiar idioma",
        ["settings.change_save_mode"] = "💾 Cambiar modo de guardado",
        ["settings.change_storage_mode"] = "💽 Cambiar modo de almacenamiento",
        ["language.current"] = "🌐 <b>Idioma</b>\n\nActual: {0}\n\nElige un nuevo idioma:",
        ["language.changed"] = "✅ Idioma cambiado a {0}",
        ["savemode.title"] = "💾 <b>Modo de guardado</b>\n\nActual: <b>{0}</b>\n\n• <b>auto</b> — guardar palabras automáticamente\n• <b>ask</b> — confirmar antes de cada guardado\n• <b>off</b> — no guardar en el deck",
        ["savemode.changed"] = "✅ Modo de guardado cambiado a <b>{0}</b>",
        ["savemode.auto"] = "💾 auto",
        ["savemode.ask"] = "❓ ask",
        ["savemode.off"] = "🚫 off",
        ["storagemode.title"] = "💽 <b>Modo de almacenamiento</b>\n\nActual: <b>{0}</b>\n\n• <b>local</b> — guardar en archivos Excel locales\n• <b>graph</b> — guardar en OneDrive mediante Microsoft Graph",
        ["storagemode.changed"] = "✅ Modo de almacenamiento cambiado a <b>{0}</b>",
        ["storagemode.local"] = "💾 local",
        ["storagemode.graph"] = "☁️ graph",
        ["vocab.save.ask"] = "¿Guardar \"{0}\" en \"{1}\"?",
        ["vocab.save.saved"] = "✅ Guardado en {0} (fila {1}).",
        ["vocab.save.duplicate"] = "ℹ️ La palabra ya existe en decks editables. Guardado omitido.",
        ["vocab.save.skip"] = "ℹ️ Guardado omitido.",
        ["vocab.save_failed"] = "⚠️ Error al guardar: {0}",
        ["vocab.save_batch_ask_hint"] = "El modo de guardado es ask. Para guardado automático por lotes, cambia a auto.",
        ["vocab.save_mode_off_hint"] = "El modo de guardado es off. Cámbialo a ask o auto en Ajustes.",
        ["vocab.save_yes"] = "✅ Guardar",
        ["vocab.save_no"] = "❌ Omitir",
        ["vocab.no_pending_save"] = "No hay solicitud de guardado pendiente.",
        ["vocab.word_unrecognized"] = "⚠️ La palabra \"{0}\" no se reconoce. Envía una palabra en inglés corregida.",
        ["vocab.word_unrecognized_with_suggestions"] = "⚠️ La palabra \"{0}\" no se reconoce. ¿Quizá quisiste decir: {1}? Envía la palabra corregida.",
        ["vocab.found_in_deck_single"] = "ℹ️ La palabra ya existe en el diccionario: {0} (fila {1}).",
        ["vocab.found_in_deck_multi_title"] = "ℹ️ Estas palabras ya existen en el diccionario:",
        ["vocab.found_in_deck_multi_item"] = "• {0}: {1} (fila {2})",
        ["onedrive.login_switched_to_graph"] = "✅ OneDrive conectado. El modo de almacenamiento cambió a <b>graph</b>.",
        ["onedrive.title"] = "☁️ <b>OneDrive / Graph</b>",
        ["onedrive.status_connected"] = "Estado: ✅ Conectado",
        ["onedrive.status_disconnected"] = "Estado: ❌ No conectado",
        ["onedrive.login"] = "🔑 Iniciar sesión en OneDrive",
        ["onedrive.logout"] = "🚪 Cerrar sesión",
        ["onedrive.login_started"] = "🔑 Para iniciar sesión, abre este enlace e introduce el código:\n\n<b>{0}</b>\n\nEnlace: {1}\n\nEl código expira en {2} minutos.",
        ["onedrive.logout_done"] = "✅ Sesión de OneDrive cerrada.",
        ["onedrive.check_status"] = "✅ Ya inicié sesión",
        ["onedrive.still_not_signed_in"] = "Aún no has iniciado sesión. ¿Intentar de nuevo?",
        ["onedrive.sync_now"] = "🔄 Sincronizar cola",
        ["onedrive.rebuild_index"] = "🧱 Reconstruir índice",
        ["onedrive.rebuild_index_warning"] = "⚠️ Reconstruir el índice puede tardar en decks grandes. ¿Iniciar ahora?",
        ["onedrive.rebuild_index_start"] = "✅ Iniciar reconstrucción",
        ["onedrive.rebuild_index_started"] = "⏳ Reconstruyendo índice. Esto puede tardar unos minutos...",
        ["onedrive.rebuild_index_suggest"] = "💡 Consejo: el índice parece vacío. Pulsa «Reconstruir índice» para importar palabras existentes de los decks de OneDrive.",
        ["onedrive.index_ready"] = "✅ El índice ya está en orden: {0} palabras en tu diccionario.",
        ["onedrive.sync_now_done"] = "✅ Sincronización completada: completadas={0}, reencoladas={1}, fallidas={2}, pendientes={3}.",
        ["onedrive.rebuild_index_done"] = "✅ Índice reconstruido desde decks editables: escaneadas={0}, indexadas={1}.",
        ["onedrive.operation_failed"] = "⚠️ Operación fallida: {0}",
        ["notion.title"] = "📝 <b>Notion</b>\n\n🚧 Esta integración está en desarrollo. ¡Próximamente!",
        ["back"] = "🔙 Atrás",
        ["language.name.uk"] = "🇺🇦 Українська",
        ["language.name.en"] = "🇬🇧 English",
        ["language.name.es"] = "🇪🇸 Español",
        ["language.name.fr"] = "🇫🇷 Français",
        ["language.name.de"] = "🇩🇪 Deutsch",
        ["language.name.pl"] = "🇵🇱 Polski",
        ["language.name.de_pl"] = "🇩🇪 Deutsch · 🇵🇱 Polski"
    };

    private static readonly IReadOnlyDictionary<string, string> German = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["menu.main.title"] = "Womit kann ich dir helfen?",
        ["menu.main.chat"] = "🗣 Chat",
        ["menu.main.vocabulary"] = "📚 Vokabeln",
        ["menu.main.shopping"] = "🛒 Einkauf",
        ["menu.main.menu"] = "🍽 Menü",
        ["menu.main.settings"] = "⚙️ Einstellungen",
        ["menu.vocabulary.title"] = "📚 Vokabeln\n\nDu hast {0} Wörter. Was machen wir?",
        ["menu.vocabulary.add"] = "➕ Wort hinzufügen",
        ["menu.vocabulary.list"] = "📋 Meine Liste",
        ["menu.vocabulary.url"] = "🔗 Aus URL",
        ["menu.vocabulary.batch"] = "📦 Batch-Modus",
        ["menu.vocabulary.back"] = "🔙 Hauptmenü",
        ["menu.shopping.title"] = "🛒 Einkauf",
        ["menu.shopping.add"] = "➕ Artikel hinzufügen",
        ["menu.shopping.list"] = "📋 Liste anzeigen",
        ["menu.shopping.delete"] = "🗑 Artikel entfernen",
        ["menu.shopping.back"] = "🔙 Hauptmenü",
        ["menu.weekly.title"] = "🍽 Wochenmenü",
        ["menu.weekly.view"] = "📅 Menü anzeigen",
        ["menu.weekly.plan"] = "🤖 Mit KI planen",
        ["menu.weekly.calories"] = "📊 Kalorien",
        ["menu.weekly.back"] = "🔙 Hauptmenü",
        ["stub.wip"] = "🚧 Diese Funktion ist in Entwicklung. Bald verfügbar!",
        ["start.welcome"] = "👋 Hi! Ich bin Lagertha — dein persönlicher Assistent.\n\nIch kann dir helfen bei:\n📚 englischen Wörtern lernen\n🛒 Einkaufsliste führen\n🍽 Wochenmenü planen\n🗣 chatten und allgemein helfen\n\nWähle einen Bereich oder schreib mir einfach!",
        ["locale.switched"] = "🌐 Sprache auf Deutsch gestellt",
        ["vocab.add.prompt"] = "Schick mir ein englisches Wort oder eine Phrase, und ich finde es für dich.",
        ["vocab.url.prompt"] = "Schick mir einen Artikel-Link, und ich extrahiere neue Wörter für dich.",
        ["vocab.batch.prompt"] = "Schick mehrere Wörter oder Phrasen in einer Nachricht (Zeilen, Kommas, Semikolons oder Sätze), und ich verarbeite sie im Batch-Modus.",
        ["vocab.list.empty"] = "Deine Vokabelliste ist leer.",
        ["vocab.list.title"] = "📋 Deine letzten Wörter:",
        ["onboarding.choose_language"] = "👋 Willkommen!\n\nBitte wähle deine Sprache:",
        ["onboarding.language_saved"] = "🎉 Super! Sprache gespeichert.\n\nHi! Ich bin Lagertha — dein persönlicher Assistent. Womit kann ich helfen?",
        ["settings.title"] = "⚙️ <b>Einstellungen</b>",
        ["settings.language"] = "🌐 Sprache",
        ["settings.save_mode"] = "💾 Speichermodus",
        ["settings.storage_mode"] = "💽 Speicherart",
        ["settings.onedrive"] = "☁️ OneDrive / Graph",
        ["settings.notion"] = "📝 Notion (bald)",
        ["settings.back"] = "🔙 Hauptmenü",
        ["settings.change_language"] = "🌐 Sprache ändern",
        ["settings.change_save_mode"] = "💾 Speichermodus ändern",
        ["settings.change_storage_mode"] = "💽 Speicherart ändern",
        ["language.current"] = "🌐 <b>Sprache</b>\n\nAktuell: {0}\n\nWähle eine neue Sprache:",
        ["language.changed"] = "✅ Sprache geändert auf {0}",
        ["savemode.title"] = "💾 <b>Speichermodus</b>\n\nAktuell: <b>{0}</b>\n\n• <b>auto</b> — Wörter automatisch speichern\n• <b>ask</b> — vor jedem Speichern fragen\n• <b>off</b> — nicht in Deck speichern",
        ["savemode.changed"] = "✅ Speichermodus geändert auf <b>{0}</b>",
        ["savemode.auto"] = "💾 auto",
        ["savemode.ask"] = "❓ ask",
        ["savemode.off"] = "🚫 off",
        ["storagemode.title"] = "💽 <b>Speicherart</b>\n\nAktuell: <b>{0}</b>\n\n• <b>local</b> — in lokale Excel-Dateien speichern\n• <b>graph</b> — in OneDrive über Microsoft Graph speichern",
        ["storagemode.changed"] = "✅ Speicherart geändert auf <b>{0}</b>",
        ["storagemode.local"] = "💾 local",
        ["storagemode.graph"] = "☁️ graph",
        ["vocab.save.ask"] = "\"{0}\" in \"{1}\" speichern?",
        ["vocab.save.saved"] = "✅ In {0} gespeichert (Zeile {1}).",
        ["vocab.save.duplicate"] = "ℹ️ Das Wort existiert bereits in beschreibbaren Decks. Speichern übersprungen.",
        ["vocab.save.skip"] = "ℹ️ Speichern übersprungen.",
        ["vocab.save_failed"] = "⚠️ Speichern fehlgeschlagen: {0}",
        ["vocab.save_batch_ask_hint"] = "Speichermodus ist ask. Für Batch-Autospeichern auf auto umstellen.",
        ["vocab.save_mode_off_hint"] = "Speichermodus ist off. In Einstellungen auf ask oder auto ändern.",
        ["vocab.save_yes"] = "✅ Speichern",
        ["vocab.save_no"] = "❌ Überspringen",
        ["vocab.no_pending_save"] = "Keine ausstehende Speicheranfrage.",
        ["vocab.word_unrecognized"] = "⚠️ Das Wort \"{0}\" wurde nicht erkannt. Sende ein korrigiertes englisches Wort.",
        ["vocab.word_unrecognized_with_suggestions"] = "⚠️ Das Wort \"{0}\" wurde nicht erkannt. Meintest du: {1}? Sende das korrigierte Wort.",
        ["vocab.found_in_deck_single"] = "ℹ️ Das Wort ist bereits im Wörterbuch: {0} (Zeile {1}).",
        ["vocab.found_in_deck_multi_title"] = "ℹ️ Diese Wörter sind bereits im Wörterbuch:",
        ["vocab.found_in_deck_multi_item"] = "• {0}: {1} (Zeile {2})",
        ["onedrive.login_switched_to_graph"] = "✅ OneDrive verbunden. Speicherart wurde auf <b>graph</b> umgestellt.",
        ["onedrive.title"] = "☁️ <b>OneDrive / Graph</b>",
        ["onedrive.status_connected"] = "Status: ✅ Verbunden",
        ["onedrive.status_disconnected"] = "Status: ❌ Nicht verbunden",
        ["onedrive.login"] = "🔑 Bei OneDrive anmelden",
        ["onedrive.logout"] = "🚪 Abmelden",
        ["onedrive.login_started"] = "🔑 Zum Anmelden öffne diesen Link und gib den Code ein:\n\n<b>{0}</b>\n\nLink: {1}\n\nCode läuft in {2} Minuten ab.",
        ["onedrive.logout_done"] = "✅ Von OneDrive abgemeldet.",
        ["onedrive.check_status"] = "✅ Ich bin angemeldet",
        ["onedrive.still_not_signed_in"] = "Noch nicht angemeldet. Noch einmal versuchen?",
        ["onedrive.sync_now"] = "🔄 Warteschlange synchronisieren",
        ["onedrive.rebuild_index"] = "🧱 Index neu aufbauen",
        ["onedrive.rebuild_index_warning"] = "⚠️ Der Neuaufbau des Index kann bei großen Decks etwas dauern. Jetzt starten?",
        ["onedrive.rebuild_index_start"] = "✅ Neuaufbau starten",
        ["onedrive.rebuild_index_started"] = "⏳ Index wird neu aufgebaut. Das kann ein paar Minuten dauern...",
        ["onedrive.rebuild_index_suggest"] = "💡 Tipp: Der Index scheint leer zu sein. Tippe auf „Index neu aufbauen“, um vorhandene Wörter aus OneDrive-Decks zu importieren.",
        ["onedrive.index_ready"] = "✅ Der Index ist bereits aktuell: {0} Wörter in deinem Wörterbuch.",
        ["onedrive.sync_now_done"] = "✅ Synchronisierung abgeschlossen: abgeschlossen={0}, erneut eingereiht={1}, fehlgeschlagen={2}, ausstehend={3}.",
        ["onedrive.rebuild_index_done"] = "✅ Index aus beschreibbaren Decks neu aufgebaut: geprüft={0}, indexiert={1}.",
        ["onedrive.operation_failed"] = "⚠️ Vorgang fehlgeschlagen: {0}",
        ["notion.title"] = "📝 <b>Notion</b>\n\n🚧 Diese Integration ist in Entwicklung. Bald verfügbar!",
        ["back"] = "🔙 Zurück",
        ["language.name.uk"] = "🇺🇦 Українська",
        ["language.name.en"] = "🇬🇧 English",
        ["language.name.es"] = "🇪🇸 Español",
        ["language.name.fr"] = "🇫🇷 Français",
        ["language.name.de"] = "🇩🇪 Deutsch",
        ["language.name.pl"] = "🇵🇱 Polski",
        ["language.name.de_pl"] = "🇩🇪 Deutsch · 🇵🇱 Polski"
    };

    private static readonly IReadOnlyDictionary<string, string> Polish = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["menu.main.title"] = "W czym mogę pomóc?",
        ["menu.main.chat"] = "🗣 Czat",
        ["menu.main.vocabulary"] = "📚 Słownictwo",
        ["menu.main.shopping"] = "🛒 Zakupy",
        ["menu.main.menu"] = "🍽 Menu",
        ["menu.main.settings"] = "⚙️ Ustawienia",
        ["menu.vocabulary.title"] = "📚 Słownictwo\n\nMasz {0} słów. Co robimy?",
        ["menu.vocabulary.add"] = "➕ Dodaj słowo",
        ["menu.vocabulary.list"] = "📋 Moja lista",
        ["menu.vocabulary.url"] = "🔗 Z URL",
        ["menu.vocabulary.batch"] = "📦 Tryb batch",
        ["menu.vocabulary.back"] = "🔙 Menu główne",
        ["menu.shopping.title"] = "🛒 Zakupy",
        ["menu.shopping.add"] = "➕ Dodaj produkt",
        ["menu.shopping.list"] = "📋 Pokaż listę",
        ["menu.shopping.delete"] = "🗑 Usuń produkt",
        ["menu.shopping.back"] = "🔙 Menu główne",
        ["menu.weekly.title"] = "🍽 Menu tygodniowe",
        ["menu.weekly.view"] = "📅 Pokaż menu",
        ["menu.weekly.plan"] = "🤖 Zaplanuj z AI",
        ["menu.weekly.calories"] = "📊 Kalorie",
        ["menu.weekly.back"] = "🔙 Menu główne",
        ["stub.wip"] = "🚧 Ta funkcja jest w trakcie rozwoju. Wkrótce dostępna!",
        ["start.welcome"] = "👋 Cześć! Jestem Lagertha — twoja osobista asystentka.\n\nMogę pomóc ci:\n📚 uczyć się słów angielskich\n🛒 prowadzić listę zakupów\n🍽 planować tygodniowe menu\n🗣 rozmawiać i pomagać w różnych sprawach\n\nWybierz sekcję albo po prostu napisz do mnie!",
        ["locale.switched"] = "🌐 Język ustawiony na polski",
        ["vocab.add.prompt"] = "Wyślij mi angielskie słowo lub frazę, a znajdę je dla ciebie.",
        ["vocab.url.prompt"] = "Wyślij mi link do artykułu, a wyciągnę z niego nowe słowa.",
        ["vocab.batch.prompt"] = "Wyślij kilka słów lub fraz w jednej wiadomości (nowe linie, przecinki, średniki albo zdania), a przetworzę je w trybie batch.",
        ["vocab.list.empty"] = "Twoja lista słownictwa jest pusta.",
        ["vocab.list.title"] = "📋 Twoje ostatnie słowa:",
        ["onboarding.choose_language"] = "👋 Witaj!\n\nWybierz język:",
        ["onboarding.language_saved"] = "🎉 Super! Język zapisany.\n\nCześć! Jestem Lagertha — twoja osobista asystentka. W czym mogę pomóc?",
        ["settings.title"] = "⚙️ <b>Ustawienia</b>",
        ["settings.language"] = "🌐 Język",
        ["settings.save_mode"] = "💾 Tryb zapisu",
        ["settings.storage_mode"] = "💽 Tryb przechowywania",
        ["settings.onedrive"] = "☁️ OneDrive / Graph",
        ["settings.notion"] = "📝 Notion (wkrótce)",
        ["settings.back"] = "🔙 Menu główne",
        ["settings.change_language"] = "🌐 Zmień język",
        ["settings.change_save_mode"] = "💾 Zmień tryb zapisu",
        ["settings.change_storage_mode"] = "💽 Zmień tryb przechowywania",
        ["language.current"] = "🌐 <b>Język</b>\n\nObecny: {0}\n\nWybierz nowy język:",
        ["language.changed"] = "✅ Język zmieniono na {0}",
        ["savemode.title"] = "💾 <b>Tryb zapisu</b>\n\nObecny: <b>{0}</b>\n\n• <b>auto</b> — zapisuj słowa automatycznie\n• <b>ask</b> — pytaj przed każdym zapisem\n• <b>off</b> — nie zapisuj do decka",
        ["savemode.changed"] = "✅ Tryb zapisu zmieniono na <b>{0}</b>",
        ["savemode.auto"] = "💾 auto",
        ["savemode.ask"] = "❓ ask",
        ["savemode.off"] = "🚫 off",
        ["storagemode.title"] = "💽 <b>Tryb przechowywania</b>\n\nObecny: <b>{0}</b>\n\n• <b>local</b> — zapisuj do lokalnych plików Excel\n• <b>graph</b> — zapisuj do OneDrive przez Microsoft Graph",
        ["storagemode.changed"] = "✅ Tryb przechowywania zmieniono na <b>{0}</b>",
        ["storagemode.local"] = "💾 local",
        ["storagemode.graph"] = "☁️ graph",
        ["vocab.save.ask"] = "Zapisać \"{0}\" do \"{1}\"?",
        ["vocab.save.saved"] = "✅ Zapisano do {0} (wiersz {1}).",
        ["vocab.save.duplicate"] = "ℹ️ Słowo już istnieje w deckach do zapisu. Zapis pominięty.",
        ["vocab.save.skip"] = "ℹ️ Zapis pominięty.",
        ["vocab.save_failed"] = "⚠️ Błąd zapisu: {0}",
        ["vocab.save_batch_ask_hint"] = "Tryb zapisu to ask. Aby auto-zapisywać batch, przełącz na auto.",
        ["vocab.save_mode_off_hint"] = "Tryb zapisu to off. Zmień w ustawieniach na ask albo auto.",
        ["vocab.save_yes"] = "✅ Zapisz",
        ["vocab.save_no"] = "❌ Pomiń",
        ["vocab.no_pending_save"] = "Brak oczekującego zapisu.",
        ["vocab.word_unrecognized"] = "⚠️ Słowo \"{0}\" nie zostało rozpoznane. Wyślij poprawione angielskie słowo.",
        ["vocab.word_unrecognized_with_suggestions"] = "⚠️ Słowo \"{0}\" nie zostało rozpoznane. Czy chodziło o: {1}? Wyślij poprawione słowo.",
        ["vocab.found_in_deck_single"] = "ℹ️ Słowo już istnieje w słowniku: {0} (wiersz {1}).",
        ["vocab.found_in_deck_multi_title"] = "ℹ️ Te słowa już istnieją w słowniku:",
        ["vocab.found_in_deck_multi_item"] = "• {0}: {1} (wiersz {2})",
        ["onedrive.login_switched_to_graph"] = "✅ OneDrive połączony. Tryb przechowywania przełączono na <b>graph</b>.",
        ["onedrive.title"] = "☁️ <b>OneDrive / Graph</b>",
        ["onedrive.status_connected"] = "Status: ✅ Połączono",
        ["onedrive.status_disconnected"] = "Status: ❌ Nie połączono",
        ["onedrive.login"] = "🔑 Zaloguj do OneDrive",
        ["onedrive.logout"] = "🚪 Wyloguj",
        ["onedrive.login_started"] = "🔑 Aby się zalogować, otwórz ten link i wpisz kod:\n\n<b>{0}</b>\n\nLink: {1}\n\nKod wygasa za {2} minut.",
        ["onedrive.logout_done"] = "✅ Wylogowano z OneDrive.",
        ["onedrive.check_status"] = "✅ Jestem zalogowany",
        ["onedrive.still_not_signed_in"] = "Nadal nie zalogowano. Spróbować ponownie?",
        ["onedrive.sync_now"] = "🔄 Synchronizuj kolejkę",
        ["onedrive.rebuild_index"] = "🧱 Przebuduj indeks",
        ["onedrive.rebuild_index_warning"] = "⚠️ Przebudowa indeksu może potrwać przy dużych deckach. Uruchomić teraz?",
        ["onedrive.rebuild_index_start"] = "✅ Uruchom przebudowę",
        ["onedrive.rebuild_index_started"] = "⏳ Przebudowuję indeks. To może potrwać kilka minut...",
        ["onedrive.rebuild_index_suggest"] = "💡 Wskazówka: indeks wygląda na pusty. Kliknij „Przebuduj indeks”, aby zaimportować istniejące słowa z decków OneDrive.",
        ["onedrive.index_ready"] = "✅ Indeks jest już gotowy: {0} słów w Twoim słowniku.",
        ["onedrive.sync_now_done"] = "✅ Synchronizacja zakończona: zakończone={0}, ponownie w kolejce={1}, błędy={2}, oczekujące={3}.",
        ["onedrive.rebuild_index_done"] = "✅ Indeks przebudowany z decków zapisywalnych: sprawdzone={0}, zindeksowane={1}.",
        ["onedrive.operation_failed"] = "⚠️ Operacja nie powiodła się: {0}",
        ["notion.title"] = "📝 <b>Notion</b>\n\n🚧 Ta integracja jest w trakcie rozwoju. Wkrótce dostępna!",
        ["back"] = "🔙 Wstecz",
        ["language.name.uk"] = "🇺🇦 Українська",
        ["language.name.en"] = "🇬🇧 English",
        ["language.name.es"] = "🇪🇸 Español",
        ["language.name.fr"] = "🇫🇷 Français",
        ["language.name.de"] = "🇩🇪 Deutsch",
        ["language.name.pl"] = "🇵🇱 Polski",
        ["language.name.de_pl"] = "🇩🇪 Deutsch · 🇵🇱 Polski"
    };

    private static readonly IReadOnlyDictionary<string, string> French = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["menu.main.title"] = "Comment puis-je t'aider ?",
        ["menu.main.chat"] = "🗣 Chat",
        ["menu.main.vocabulary"] = "📚 Vocabulaire",
        ["menu.main.shopping"] = "🛒 Courses",
        ["menu.main.menu"] = "🍽 Menu",
        ["menu.main.settings"] = "⚙️ Paramètres",
        ["menu.vocabulary.title"] = "📚 Vocabulaire\n\nTu as {0} mots. Que fait-on ?",
        ["menu.vocabulary.add"] = "➕ Ajouter un mot",
        ["menu.vocabulary.list"] = "📋 Ma liste",
        ["menu.vocabulary.url"] = "🔗 Depuis une URL",
        ["menu.vocabulary.batch"] = "📦 Mode batch",
        ["menu.vocabulary.back"] = "🔙 Menu principal",
        ["menu.shopping.title"] = "🛒 Courses",
        ["menu.shopping.add"] = "➕ Ajouter un article",
        ["menu.shopping.list"] = "📋 Voir la liste",
        ["menu.shopping.delete"] = "🗑 Supprimer un article",
        ["menu.shopping.back"] = "🔙 Menu principal",
        ["menu.weekly.title"] = "🍽 Menu de la semaine",
        ["menu.weekly.view"] = "📅 Voir le menu",
        ["menu.weekly.plan"] = "🤖 Planifier avec l'IA",
        ["menu.weekly.calories"] = "📊 Calories",
        ["menu.weekly.back"] = "🔙 Menu principal",
        ["stub.wip"] = "🚧 Cette fonctionnalité est en cours de développement. Bientôt disponible !",
        ["start.welcome"] = "👋 Salut ! Je suis Lagertha — ton assistante personnelle.\n\nJe peux t'aider à :\n📚 apprendre des mots anglais\n🛒 gérer une liste de courses\n🍽 planifier ton menu hebdomadaire\n🗣 discuter et t'aider sur tout\n\nChoisis une section ou écris-moi directement !",
        ["locale.switched"] = "🌐 Langue définie sur le français",
        ["vocab.add.prompt"] = "Envoie-moi un mot ou une expression en anglais et je le trouverai pour toi.",
        ["vocab.url.prompt"] = "Envoie-moi l'URL d'un article et j'extrairai de nouveaux mots pour toi.",
        ["vocab.batch.prompt"] = "Envoie plusieurs mots ou expressions dans un seul message (lignes, virgules, points-virgules ou phrases), et je les traiterai en mode batch.",
        ["vocab.list.empty"] = "Ta liste de vocabulaire est vide.",
        ["vocab.list.title"] = "📋 Tes derniers mots :",
        ["onboarding.choose_language"] = "👋 Bienvenue !\n\nChoisis ta langue :",
        ["onboarding.language_saved"] = "🎉 Super ! Langue enregistrée.\n\nSalut ! Je suis Lagertha — ton assistante personnelle. Comment puis-je t'aider ?",
        ["settings.title"] = "⚙️ <b>Paramètres</b>",
        ["settings.language"] = "🌐 Langue",
        ["settings.save_mode"] = "💾 Mode de sauvegarde",
        ["settings.storage_mode"] = "💽 Mode de stockage",
        ["settings.onedrive"] = "☁️ OneDrive / Graph",
        ["settings.notion"] = "📝 Notion (bientôt)",
        ["settings.back"] = "🔙 Menu principal",
        ["settings.change_language"] = "🌐 Changer la langue",
        ["settings.change_save_mode"] = "💾 Changer le mode de sauvegarde",
        ["settings.change_storage_mode"] = "💽 Changer le mode de stockage",
        ["language.current"] = "🌐 <b>Langue</b>\n\nActuelle : {0}\n\nChoisis une nouvelle langue :",
        ["language.changed"] = "✅ Langue changée vers {0}",
        ["savemode.title"] = "💾 <b>Mode de sauvegarde</b>\n\nActuel : <b>{0}</b>\n\n• <b>auto</b> — sauvegarder automatiquement\n• <b>ask</b> — demander une confirmation à chaque sauvegarde\n• <b>off</b> — ne pas sauvegarder dans le deck",
        ["savemode.changed"] = "✅ Mode de sauvegarde changé vers <b>{0}</b>",
        ["savemode.auto"] = "💾 auto",
        ["savemode.ask"] = "❓ ask",
        ["savemode.off"] = "🚫 off",
        ["storagemode.title"] = "💽 <b>Mode de stockage</b>\n\nActuel : <b>{0}</b>\n\n• <b>local</b> — sauvegarder dans des fichiers Excel locaux\n• <b>graph</b> — sauvegarder dans OneDrive via Microsoft Graph",
        ["storagemode.changed"] = "✅ Mode de stockage changé vers <b>{0}</b>",
        ["storagemode.local"] = "💾 local",
        ["storagemode.graph"] = "☁️ graph",
        ["vocab.save.ask"] = "Sauvegarder \"{0}\" dans \"{1}\" ?",
        ["vocab.save.saved"] = "✅ Sauvegardé dans {0} (ligne {1}).",
        ["vocab.save.duplicate"] = "ℹ️ Le mot existe déjà dans les decks modifiables. Sauvegarde ignorée.",
        ["vocab.save.skip"] = "ℹ️ Sauvegarde ignorée.",
        ["vocab.save_failed"] = "⚠️ Échec de la sauvegarde : {0}",
        ["vocab.save_batch_ask_hint"] = "Le mode de sauvegarde est ask. Pour l'auto-sauvegarde en batch, passe le mode de sauvegarde à auto.",
        ["vocab.save_mode_off_hint"] = "Le mode de sauvegarde est off. Change-le vers ask ou auto dans les paramètres.",
        ["vocab.save_yes"] = "✅ Sauvegarder",
        ["vocab.save_no"] = "❌ Ignorer",
        ["vocab.no_pending_save"] = "Aucune sauvegarde en attente.",
        ["vocab.word_unrecognized"] = "⚠️ Le mot \"{0}\" n'est pas reconnu. Envoie un mot anglais corrigé.",
        ["vocab.word_unrecognized_with_suggestions"] = "⚠️ Le mot \"{0}\" n'est pas reconnu. Vouliez-vous dire : {1} ? Envoie le mot corrigé.",
        ["vocab.found_in_deck_single"] = "ℹ️ Le mot existe déjà dans le dictionnaire : {0} (ligne {1}).",
        ["vocab.found_in_deck_multi_title"] = "ℹ️ Ces mots existent déjà dans le dictionnaire :",
        ["vocab.found_in_deck_multi_item"] = "• {0} : {1} (ligne {2})",
        ["onedrive.login_switched_to_graph"] = "✅ OneDrive connecté. Le mode de stockage a été basculé vers <b>graph</b>.",
        ["onedrive.title"] = "☁️ <b>OneDrive / Graph</b>",
        ["onedrive.status_connected"] = "Statut : ✅ Connecté",
        ["onedrive.status_disconnected"] = "Statut : ❌ Non connecté",
        ["onedrive.login"] = "🔑 Se connecter à OneDrive",
        ["onedrive.logout"] = "🚪 Se déconnecter",
        ["onedrive.login_started"] = "🔑 Pour te connecter, ouvre ce lien et saisis le code :\n\n<b>{0}</b>\n\nLien : {1}\n\nLe code expire dans {2} minutes.",
        ["onedrive.logout_done"] = "✅ Déconnecté de OneDrive.",
        ["onedrive.check_status"] = "✅ Je suis connecté",
        ["onedrive.still_not_signed_in"] = "Toujours non connecté. Réessayer ?",
        ["onedrive.sync_now"] = "🔄 Synchroniser la file",
        ["onedrive.rebuild_index"] = "🧱 Reconstruire l’index",
        ["onedrive.rebuild_index_warning"] = "⚠️ La reconstruction de l’index peut prendre du temps sur de grands decks. Démarrer maintenant ?",
        ["onedrive.rebuild_index_start"] = "✅ Démarrer la reconstruction",
        ["onedrive.rebuild_index_started"] = "⏳ Reconstruction de l’index en cours. Cela peut prendre quelques minutes...",
        ["onedrive.rebuild_index_suggest"] = "💡 Conseil : l’index semble vide. Appuie sur « Reconstruire l’index » pour importer les mots existants des decks OneDrive.",
        ["onedrive.index_ready"] = "✅ Index déjà prêt : {0} mots dans ton dictionnaire.",
        ["onedrive.sync_now_done"] = "✅ Synchronisation terminée : terminés={0}, remis en file={1}, en échec={2}, en attente={3}.",
        ["onedrive.rebuild_index_done"] = "✅ Index reconstruit depuis les decks modifiables : analysés={0}, indexés={1}.",
        ["onedrive.operation_failed"] = "⚠️ Échec de l’opération : {0}",
        ["notion.title"] = "📝 <b>Notion</b>\n\n🚧 Cette intégration est en cours de développement. Bientôt disponible !",
        ["back"] = "🔙 Retour",
        ["language.name.uk"] = "🇺🇦 Українська",
        ["language.name.en"] = "🇬🇧 English",
        ["language.name.es"] = "🇪🇸 Español",
        ["language.name.fr"] = "🇫🇷 Français",
        ["language.name.de"] = "🇩🇪 Deutsch",
        ["language.name.pl"] = "🇵🇱 Polski",
        ["language.name.de_pl"] = "🇩🇪 Deutsch · 🇵🇱 Polski"
    };

    public string Get(string key, string locale)
    {
        var normalizedLocale = LocalizationConstants.NormalizeLocaleCode(locale);

        var dictionary = normalizedLocale switch
        {
            LocalizationConstants.UkrainianLocale => Ukrainian,
            LocalizationConstants.SpanishLocale => Spanish,
            LocalizationConstants.FrenchLocale => French,
            LocalizationConstants.GermanLocale => German,
            LocalizationConstants.PolishLocale => Polish,
            _ => English
        };

        if (dictionary.TryGetValue(key, out var value))
        {
            return value;
        }

        if (English.TryGetValue(key, out var fallback))
        {
            if (!string.Equals(normalizedLocale, LocalizationConstants.EnglishLocale, StringComparison.Ordinal))
            {
                _logger?.LogDebug(
                    "Localization key '{Key}' missing for locale '{Locale}', using 'en' fallback.",
                    key,
                    normalizedLocale);
            }

            return fallback;
        }

        _logger?.LogWarning(
            "Localization key '{Key}' missing for all locales including 'en'. Returning placeholder.",
            key);
        return $"[?:{key}]";
    }

    public string GetLocaleForUser(string? telegramLanguageCode)
        => LocalizationConstants.NormalizeLocaleCode(telegramLanguageCode);

    public bool IsRussian(string? languageCode)
        => languageCode?.StartsWith("ru", StringComparison.OrdinalIgnoreCase) == true;
}
