using LagerthaAssistant.Application.Constants;
using LagerthaAssistant.Application.Interfaces;
using Microsoft.Extensions.Logging;

namespace LagerthaAssistant.Infrastructure.Services;

public sealed class LocalizationService : ILocalizationService
{
    private readonly ILogger<LocalizationService>? _logger;

    public LocalizationService(ILogger<LocalizationService>? logger = null)
    {
        _logger = logger;
    }

    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["menu.main.title"] = "What can I help you with?",
        ["menu.chat.title"] = "🗣 Chat mode enabled. Ask me in natural language — I can explain features and perform supported actions.",
        ["menu.main.chat"] = "🗣 Chat",
        ["menu.main.vocabulary"] = "📚 Vocabulary",
        ["menu.main.shopping"] = "🛒 Shopping",
        ["menu.main.menu"] = "🍽 Menu",
        ["menu.main.settings"] = "⚙️ Settings",
        ["menu.vocabulary.title"] = "📚 Vocabulary\n\nYou have {0} words. What shall we do?",
        ["menu.vocabulary.add"] = "➕ Add word",
        ["menu.vocabulary.stats"] = "📊 Statistics",
        ["menu.vocabulary.url"] = "📥 Import",
        ["menu.vocabulary.batch"] = "📦 Batch mode",
        ["menu.vocabulary.back"] = "🔙 Main menu",
        ["menu.shopping.title"] = "🛒 Shopping",
        ["menu.shopping.add"] = "➕ Add item",
        ["menu.shopping.list"] = "📋 View list",
        ["menu.shopping.delete"] = "🗑 Remove item",
        ["menu.shopping.back"] = "🔙 Inventory",
        ["menu.food.title"] = "🍱 Food",
        ["menu.food.inventory"] = "🏪 Inventory",
        ["menu.food.shopping"] = "🛍 Shopping List",
        ["menu.food.back"] = "🔙 Main menu",
        ["menu.inventory.title"] = "🏪 Inventory",
        ["menu.inventory.list"] = "📋 All items",
        ["menu.inventory.search"] = "🔍 Search",
        ["menu.inventory.add"] = "➕ New item",
        ["menu.inventory.suggest"] = "💡 Suggest purchases",
        ["menu.inventory.back"] = "🔙 Main menu",
        ["inventory.empty"] = "Inventory is empty. Add items via Notion or use ➕ New item.",
        ["inventory.search.prompt"] = "Type the item name to search the inventory:",
        ["inventory.add.prompt"] = "Type the name of the new inventory item:",
        ["inventory.added"] = "Added \"{0}\" to inventory.",
        ["inventory.cart.added"] = "Added \"{0}\" to your shopping list.",
        ["inventory.cart.not_found"] = "Item not found in inventory.",
        ["inventory.suggest.empty"] = "No purchase suggestions — inventory has no items with minimum quantity set.",
        ["shop.not_in_inventory"] = "⚠️ \"{0}\" was not found in inventory, so it was not added to shopping list.",
        ["shop.only_english"] = "⚠️ Product name must be in English. Shopping list accepts inventory items only.",
        ["shop.add_inventory_first"] = "Add this product to inventory first (in English), then add it to shopping list.",
        ["shop.matched_inventory"] = "Matched inventory item: \"{0}\".",
        ["menu.weekly.title"] = "🍽 Weekly Menu",
        ["menu.weekly.view"] = "📅 View menu",
        ["menu.weekly.plan"] = "🤖 Plan with AI",
        ["menu.weekly.calories"] = "📊 Calories",
        ["menu.weekly.favourites"] = "⭐ Favourites",
        ["menu.weekly.log"] = "✍️ Log meal",
        ["menu.weekly.create"] = "➕ Create meal",
        ["menu.weekly.analytics"] = "📊 Analytics",
        ["menu.weekly.back"] = "🔙 Main menu",
        ["meal.create.confirm"] = "✅ Create",
        ["meal.create.cancel"] = "❌ Cancel",
        ["menu.weekly.goal"] = "🎯 Daily Goal",
        ["menu.weekly.diversity"] = "🥗 Diversity",
        ["food.photo.confirm"] = "✅ Log this",
        ["food.photo.cancel"] = "❌ Cancel",
        ["food.shop.list.empty"] = "Shopping list is empty.",
        ["food.shop.list.title"] = "Shopping list ({0} items):",
        ["food.shop.list.no_store"] = "No store",
        ["food.shop.list.store"] = "📍 {0}",
        ["food.shop.list.item"] = "  • {0}{1}{2}",
        ["food.shop.add.prompt"] = "What would you like to add to the shopping list? Type an ENGLISH item name (optionally quantity and store, e.g. \"Milk 2L SuperMart\").",
        ["food.shop.clear.none"] = "No bought items to clear.",
        ["food.shop.clear.done"] = "Cleared {0} bought item(s) from the list.",
        ["food.shop.added"] = "Added \"{0}\"{1}{2} to your shopping list.",
        ["food.weekly.view.empty"] = "No meals found. Add some meals to Notion Meal Plans first.",
        ["food.weekly.view.title"] = "Meal plans ({0} meals):",
        ["food.weekly.view.ingredients"] = "  Ingredients: {0}{1}",
        ["food.weekly.cookable.empty"] = "No meals can be prepared with the current inventory. Try syncing from Notion or adding items to your inventory.",
        ["food.weekly.cookable.title"] = "You can cook right now ({0} options):",
        ["food.weekly.calories.empty"] = "No calorie data for the past 7 days.",
        ["food.weekly.calories.title"] = "📊 Calories — last 7 days ({0} – {1})",
        ["food.weekly.calories.total"] = "Total:   {0} kcal",
        ["food.weekly.calories.avg"] = "Average: {0:F0} kcal/day",
        ["food.weekly.calories.protein"] = "Protein: {0:F0} g",
        ["food.weekly.calories.carbs"] = "Carbs:   {0:F0} g",
        ["food.weekly.calories.fat"] = "Fat:     {0:F0} g",
        ["food.weekly.favourites.empty"] = "No meal history yet. Log your meals to build your favourites list.",
        ["food.weekly.favourites.title"] = "⭐ Your top meals ({0}):",
        ["food.weekly.log.empty"] = "No meals found. Add meals in Notion Meal Plans first, then sync.",
        ["food.weekly.log.prompt"] = "Which meal did you eat? Reply with the meal ID and optional servings:\n  Format: <id>  or  <id> <servings>  (e.g. \"5\" or \"5 2.5\")",
        ["food.weekly.create.prompt"] = "What meal would you like to create? Type the name (e.g. \"Chicken Curry\" or \"Pasta Carbonara\").",
        ["food.weekly.goal.title"] = "🎯 Daily progress — {0}",
        ["food.weekly.goal.consumed"] = "Consumed: {0} / {1} kcal",
        ["food.weekly.goal.remaining"] = "Remaining: {0} kcal",
        ["food.weekly.goal.meals"] = "Meals logged: {0}",
        ["food.weekly.diversity.empty"] = "No meals logged in the past 7 days.",
        ["food.weekly.diversity.title"] = "🥗 Diet diversity — last {0} days",
        ["food.weekly.diversity.total"] = "Total meals: {0}",
        ["food.weekly.diversity.unique"] = "Unique meals: {0}",
        ["food.weekly.diversity.repeated"] = "Most repeated:",
        ["food.weekly.diversity.score"] = "Diversity score: {0:F0}% unique",
        ["food.unknown"] = "Use the buttons to navigate Shopping or Weekly Menu.",
        ["stub.wip"] = "🚧 This feature is under development. Coming soon!",
        ["start.welcome"] = "👋 Hi! I'm Lagertha — your personal assistant.\n\nI can help you:\n📚 Learn English words\n🛒 Keep a shopping list\n🍽 Plan your weekly menu\n🗣 Chat and help with anything\n\nChoose a section or just write to me!",
        ["locale.switched"] = "🌐 Language set to English",
        ["vocab.add.prompt"] = "Send me a word or phrase in English and I'll look it up for you.",
        ["vocab.import.choose_source"] = "Choose import source:",
        ["vocab.import.source.photo"] = "🖼 Photo",
        ["vocab.import.source.file"] = "📄 File",
        ["vocab.import.source.url"] = "🔗 URL",
        ["vocab.import.source.text"] = "📝 Text",
        ["vocab.import.prompt.photo"] = "Send a photo with English text, and I will extract words from it.",
        ["vocab.import.prompt.file"] = "Send a file (.txt, .md, .csv, .log, .json, .pdf, .xlsx, .xls, .xlsm), and I will extract words from it.",
        ["vocab.import.prompt.url"] = "Send an article URL, and I will suggest new words.",
        ["vocab.import.prompt.text"] = "Send article text, and I will suggest new words.",
        ["vocab.import.invalid_expected_photo"] = "⚠️ Waiting for a photo. Send a photo or choose another source.",
        ["vocab.import.invalid_expected_file"] = "⚠️ Waiting for a file. Send a supported file or choose another source.",
        ["vocab.import.invalid_expected_url"] = "⚠️ Waiting for a valid URL. Send a link starting with http:// or https://.",
        ["vocab.import.invalid_expected_text"] = "⚠️ Waiting for plain text. Paste text or choose another source.",
        ["vocab.import.file_unsupported"] = "⚠️ Unsupported file type. Supported: .txt, .md, .csv, .log, .json, .pdf, .xlsx, .xls, .xlsm.",
        ["vocab.import.photo_no_text"] = "ℹ️ I couldn't extract readable text from this photo.",
        ["vocab.import.file_no_text"] = "ℹ️ I couldn't extract readable text from this file.",
        ["vocab.import.read_failed"] = "⚠️ Import failed: {0}",
        ["vocab.url.prompt"] = "Send me an article URL or paste text to import, and I'll suggest new words.",
        ["vocab.url.processing"] = "🔎 Analyzing source... This can take a few seconds.",
        ["vocab.url.invalid"] = "⚠️ I couldn't read this source. Send a valid URL or paste readable article text.",
        ["vocab.url.empty"] = "ℹ️ I couldn't find new noun/verb/adjective words in this source.",
        ["vocab.url.suggestions_title"] = "🔎 Suggested new words: {0}",
        ["vocab.url.suggestions_group_n"] = "Nouns",
        ["vocab.url.suggestions_group_v"] = "Verbs",
        ["vocab.url.suggestions_group_adj"] = "Adjectives",
        ["vocab.url.suggestions_hint"] = "❓Reply with numbers to add (example: 1,3,7). You can also use the buttons below.",
        ["vocab.url.select_parse_failed"] = "⚠️ I couldn't parse your selection. Send numbers like 1,3,7 or use the buttons.",
        ["vocab.url.selection_cancelled"] = "ℹ️ Import cancelled.",
        ["vocab.url.no_pending"] = "No pending import request.",
        ["vocab.url.select_all"] = "✅ Add all suggested words",
        ["vocab.url.cancel"] = "❌ Cancel import",
        ["vocab.batch.prompt"] = "Send several words or phrases in one message (new lines, commas, semicolons, or sentences), and I will process them in batch mode.",
        ["vocab.stats.empty"] = "Vocabulary index is empty. Add words to build your statistics.",
        ["vocab.stats.title"] = "📊 Vocabulary statistics",
        ["vocab.stats.total"] = "Total indexed words: {0}",
        ["vocab.stats.summary"] = "Decks: {0} | POS markers: {1}",
        ["vocab.stats.by_marker"] = "By part of speech:",
        ["vocab.stats.top_decks"] = "Top decks:",
        ["vocab.stats.no_data"] = "• No data yet",
        ["vocab.stats.marker_unknown"] = "(unclassified)",
        ["vocab.stats.item"] = "• {0}: {1}",
        ["vocab.stats.deck_item"] = "{0}) {1} — {2}",
        ["vocab.stats.and_more_decks"] = "… and {0} more deck(s).",
        ["onboarding.choose_language"] = "👋 Welcome!\n\nPlease choose your language:",
        ["onboarding.language_saved"] = "🎉 Great! Language saved.\n\nHi! I'm Lagertha — your personal assistant. How can I help?",
        ["settings.title"] = "⚙️ <b>Settings</b>",
        ["settings.language"] = "🌐 Language",
        ["settings.save_mode"] = "💾 Save mode",
        ["settings.ai"] = "🤖 AI",
        ["settings.storage_mode"] = "💽 Storage mode",
        ["settings.onedrive"] = "☁️ OneDrive / Graph",
        ["settings.notion"] = "📝 Notion",
        ["settings.notion_enabled"] = "✅ Enabled",
        ["settings.notion_partial"] = "⚠️ Needs setup",
        ["settings.notion_disabled"] = "⏸ Disabled",
        ["settings.back"] = "🔙 Main menu",
        ["settings.change_language"] = "🌐 Change language",
        ["settings.change_save_mode"] = "💾 Change save mode",
        ["settings.change_ai"] = "🤖 Change AI",
        ["settings.change_storage_mode"] = "💽 Change storage mode",
        ["ai.title"] = "🤖 <b>AI settings</b>",
        ["ai.provider.label"] = "Provider",
        ["ai.model.label"] = "Model",
        ["ai.key.label"] = "API key",
        ["ai.key.status.stored"] = "stored in app",
        ["ai.key.status.environment"] = "from environment",
        ["ai.key.status.missing"] = "not set",
        ["ai.provider.change"] = "🔁 Change provider",
        ["ai.model.change"] = "🧠 Change model",
        ["ai.key.set"] = "🔑 Set API key",
        ["ai.key.remove"] = "🗑 Remove API key",
        ["ai.provider.title"] = "🔁 <b>AI provider</b>\n\nCurrent: <b>{0}</b>\n\nChoose provider:",
        ["ai.provider.changed"] = "✅ AI provider changed to <b>{0}</b>.",
        ["ai.model.title"] = "🧠 <b>AI model</b>\n\nChoose model for provider {0}:",
        ["ai.model.current"] = "Current",
        ["ai.model.changed"] = "✅ AI model changed to <code>{0}</code>.",
        ["ai.key.prompt"] = "❓ Send API key for selected provider.\n\nType <code>/cancel</code> to abort.",
        ["ai.key.saved"] = "✅ API key saved for {0}.",
        ["ai.key.removed"] = "✅ API key removed for {0}.",
        ["ai.key.cancelled"] = "ℹ️ API key update cancelled.",
        ["ai.key.save_failed"] = "⚠️ Failed to save API key. Please try again.",
        ["language.current"] = "🌐 <b>Language</b>\n\nCurrent: {0}\n\nChoose new language:",
        ["language.changed"] = "✅ Language changed to {0}",
        ["savemode.title"] = "💾 <b>Save mode</b>\n\nCurrent: <b>{0}</b>\n\n• <b>auto</b> — save words automatically\n• <b>ask</b> — confirm before each save\n• <b>off</b> — don't save to deck",
        ["savemode.changed"] = "✅ Save mode changed to <b>{0}</b>",
        ["savemode.auto"] = "💾 auto",
        ["savemode.ask"] = "❓ ask",
        ["savemode.off"] = "🚫 off",
        ["storagemode.title"] = "💽 <b>Storage mode</b>\n\nCurrent: <b>{0}</b>\n\n• <b>local</b> — save to local Excel files\n• <b>graph</b> — save to OneDrive via Microsoft Graph",
        ["storagemode.changed"] = "✅ Storage mode changed to <b>{0}</b>",
        ["storagemode.local"] = "💾 local",
        ["storagemode.graph"] = "☁️ graph",
        ["vocab.save.ask"] = "Save \"{0}\" to \"{1}\"?",
        ["vocab.save.saved"] = "✅ Saved to {0} (row {1}).",
        ["vocab.save.duplicate"] = "ℹ️ Word already exists in writable decks. Save skipped.",
        ["vocab.save.skip"] = "ℹ️ Save skipped.",
        ["vocab.save_failed"] = "⚠️ Save failed: {0}",
        ["vocab.save_missing_deck"] = "⚠️ Save queued, but target deck file is missing in OneDrive: {0}. Add this file (or fix mapping), then run sync.",
        ["vocab.deck_unknown"] = "(unknown deck)",
        ["vocab.save_queued_waiting_auth"] = "⏳ Saved to queue. It will be synced to OneDrive files after you sign in (Settings -> OneDrive / Graph).",
        ["vocab.save_batch_ask_hint"] = "ℹ️ Save mode is ask. For batch auto-save, switch save mode to auto.",
        ["vocab.save_batch_ask_question"] = "Save all {0} new items from this batch?",
        ["vocab.save_batch_done"] = "✅ Batch save finished: saved={0}, duplicates={1}, failed={2}.",
        ["vocab.save_batch_skip"] = "ℹ️ Batch save skipped.",
        ["vocab.save_mode_off_hint"] = "Save mode is off. Switch it to ask or auto in Settings.",
        ["vocab.save_yes"] = "✅ Save",
        ["vocab.save_no"] = "❌ Skip",
        ["vocab.save_batch_yes"] = "✅ Save all",
        ["vocab.save_batch_no"] = "❌ Skip all",
        ["vocab.no_pending_save"] = "No pending save request.",
        ["vocab.word_unrecognized"] = "⚠️ Word \"{0}\" is not recognized. Send a corrected English word.",
        ["vocab.word_unrecognized_with_suggestions"] = "⚠️ Word \"{0}\" is not recognized. Did you mean: {1}? Send the corrected word.",
        ["vocab.found_in_deck_single"] = "ℹ️ Word already exists in dictionary: {0} (row {1}).",
        ["vocab.found_in_deck_multi_title"] = "ℹ️ These words already exist in dictionary:",
        ["vocab.found_in_deck_multi_item"] = "• {0}: {1} (row {2})",
        ["vocab.graph_save_setup_required"] = "To save words, open Settings -> OneDrive / Graph, sign in, and try again.",
        ["command.console_only_generic"] = "⚠️ The {0} command is available only in the console app. In Telegram, use menu buttons or natural language.",
        ["command.console_only_graph"] = "⚠️ The {0} command is console-only. To save words in Telegram, open Settings -> OneDrive / Graph and sign in.",
        ["onedrive.login_switched_to_graph"] = "✅ OneDrive connected. Storage mode switched to <b>graph</b>.",
        ["onedrive.title"] = "☁️ <b>OneDrive / Graph</b>",
        ["onedrive.status_connected"] = "Status: ✅ Connected",
        ["onedrive.status_disconnected"] = "Status: ❌ Not connected",
        ["onedrive.error_not_authenticated"] = "OneDrive authorization is required. Open Settings -> OneDrive / Graph and sign in.",
        ["onedrive.error_expired"] = "OneDrive session expired. Open Settings -> OneDrive / Graph and sign in again.",
        ["onedrive.error_not_configured"] = "Graph integration is not configured on the server.",
        ["onedrive.error_timed_out"] = "Login timed out. Try sign-in again from Settings -> OneDrive / Graph.",
        ["onedrive.error_declined"] = "Login was declined. Try sign-in again from Settings -> OneDrive / Graph.",
        ["onedrive.login"] = "🔑 Sign in to OneDrive",
        ["onedrive.logout"] = "🚪 Sign out",
        ["onedrive.login_started"] = "🔑 To sign in, open this link and enter the code:\n\n<b>{0}</b>\n\nLink: {1}\n\nCode expires in {2} minutes.",
        ["onedrive.logout_done"] = "✅ Signed out from OneDrive.",
        ["onedrive.check_status"] = "✅ I've signed in",
        ["onedrive.still_not_signed_in"] = "Still not signed in. Try again?",
        ["onedrive.sync_now"] = "🔄 Sync pending saves",
        ["onedrive.rebuild_index"] = "🧱 Rebuild cache",
        ["onedrive.rebuild_index_warning"] = "⚠️ Rebuilding cache can take some time on large decks. Start now?",
        ["onedrive.rebuild_index_start"] = "✅ Start rebuild",
        ["onedrive.rebuild_index_started"] = "⏳ Rebuilding cache. This may take a few minutes...",
        ["onedrive.rebuild_index_suggest"] = "💡 Tip: cache appears empty. Tap “Rebuild cache” to import existing words from OneDrive decks.",
        ["onedrive.index_ready"] = "✅ Cache is already up to date: {0} words in your dictionary.",
        ["onedrive.sync_now_done"] = "✅ Sync complete: completed={0}, requeued={1}, failed={2}, pending={3}.",
        ["onedrive.rebuild_index_done"] = "✅ Cache rebuilt from writable decks: scanned={0}, indexed={1}.",
        ["onedrive.clear_cache"] = "🧹 Clear cache",
        ["onedrive.clear_cache_warning"] = "⚠️ Clear dictionary cache in database? Records to delete: {0}. This does NOT remove anything from OneDrive files.",
        ["onedrive.clear_cache_start"] = "✅ Clear cache now",
        ["onedrive.clear_cache_done"] = "✅ Cache cleared: deleted {0} record(s) from database.",
        ["onedrive.clear_cache_hint"] = "💡 If needed, run “Rebuild cache” to import words from writable decks again.",
        ["onedrive.decks_missing_title"] = "⚠️ Missing configured target decks in OneDrive ({0}):",
        ["onedrive.decks_missing_item"] = "• {0} → <code>{1}</code>",
        ["onedrive.decks_missing_hint"] = "⏳ Saves for these targets stay in queue. Add files (or update mapping) and tap “Sync pending saves”.",
        ["onedrive.operation_failed"] = "⚠️ Operation failed: {0}",
        ["notion.title"] = "📝 <b>Notion</b>",
        ["notion.vocabulary"] = "Vocabulary export",
        ["notion.food"] = "Food sync",
        ["notion.status_enabled"] = "✅ Enabled",
        ["notion.status_disabled"] = "⏸ Disabled",
        ["notion.configured_yes"] = "✅ Configured",
        ["notion.configured_no"] = "⚠️ Missing required keys",
        ["notion.worker_enabled"] = "✅ Worker enabled",
        ["notion.worker_disabled"] = "⏸ Worker disabled",
        ["notion.tip"] = "Set Notion keys in Railway variables if you want syncing to run.",
        ["back"] = "🔙 Back",
        ["language.name.uk"] = "🇺🇦 Українська",
        ["language.name.en"] = "🇬🇧 English"
    };

    private static readonly IReadOnlyDictionary<string, string> Ukrainian = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["menu.main.title"] = "Чим можу допомогти?",
        ["menu.chat.title"] = "🗣 Режим чату увімкнено. Пиши звичайною мовою — я поясню функції та виконаю доступні дії.",
        ["menu.main.chat"] = "🗣 Чат",
        ["menu.main.vocabulary"] = "📚 Словник",
        ["menu.main.shopping"] = "🛒 Запаси",
        ["menu.main.menu"] = "🍽 Меню",
        ["menu.main.settings"] = "⚙️ Налаштування",
        ["menu.vocabulary.title"] = "📚 Словник\n\nУ тебе {0} слів. Що зробимо?",
        ["menu.vocabulary.add"] = "➕ Додати слово",
        ["menu.vocabulary.stats"] = "📊 Статистика",
        ["menu.vocabulary.url"] = "📥 Імпорт",
        ["menu.vocabulary.batch"] = "📦 Batch режим",
        ["menu.vocabulary.back"] = "🔙 Головне меню",
        ["menu.shopping.title"] = "🛒 Покупки",
        ["menu.shopping.add"] = "➕ Додати товар",
        ["menu.shopping.list"] = "📋 Список",
        ["menu.shopping.delete"] = "🗑 Видалити товар",
        ["menu.shopping.back"] = "🔙 Склад",
        ["menu.food.title"] = "📦 Запаси",
        ["menu.food.inventory"] = "🏪 Склад",
        ["menu.food.shopping"] = "🛍 Список покупок",
        ["menu.food.back"] = "🔙 Головне меню",
        ["menu.inventory.title"] = "🏪 Склад",
        ["menu.inventory.list"] = "📋 Всі товари",
        ["menu.inventory.search"] = "🔍 Пошук",
        ["menu.inventory.add"] = "➕ Новий товар",
        ["menu.inventory.suggest"] = "💡 Що купити?",
        ["menu.inventory.back"] = "🔙 Головне меню",
        ["inventory.empty"] = "Склад порожній. Додайте товари через Notion або натисніть ➕ Новий товар.",
        ["inventory.search.prompt"] = "Введіть назву товару для пошуку:",
        ["inventory.add.prompt"] = "Введіть назву нового товару:",
        ["inventory.added"] = "Додано \"{0}\" до складу.",
        ["inventory.cart.added"] = "Додано \"{0}\" до списку покупок.",
        ["inventory.cart.not_found"] = "Товар не знайдено на складі.",
        ["inventory.suggest.empty"] = "Немає пропозицій — на складі не задано мінімальну кількість.",
        ["shop.not_in_inventory"] = "⚠️ \"{0}\" не знайдено на складі, тому товар не додано у список покупок.",
        ["shop.only_english"] = "⚠️ Назва товару має бути англійською. У список покупок додаються тільки товари зі складу.",
        ["shop.add_inventory_first"] = "Спочатку додайте цей товар на склад англійською, а потім додайте його у список покупок.",
        ["shop.matched_inventory"] = "Знайдено на складі: \"{0}\".",
        ["menu.weekly.title"] = "🍽 Меню на тиждень",
        ["menu.weekly.view"] = "📅 Переглянути меню",
        ["menu.weekly.plan"] = "🤖 Запропонуй меню",
        ["menu.weekly.calories"] = "📊 Калорії",
        ["menu.weekly.favourites"] = "⭐ Улюблені",
        ["menu.weekly.log"] = "✍️ Записати прийом",
        ["menu.weekly.create"] = "➕ Створити страву",
        ["menu.weekly.analytics"] = "📊 Аналітика",
        ["menu.weekly.back"] = "🔙 Головне меню",
        ["meal.create.confirm"] = "✅ Створити",
        ["meal.create.cancel"] = "❌ Скасувати",
        ["menu.weekly.goal"] = "🎯 Ціль дня",
        ["menu.weekly.diversity"] = "🥗 Різноманітність",
        ["food.photo.confirm"] = "✅ Записати",
        ["food.photo.cancel"] = "❌ Скасувати",
        ["food.shop.list.empty"] = "Список покупок порожній.",
        ["food.shop.list.title"] = "Список покупок ({0}):",
        ["food.shop.list.no_store"] = "Без магазину",
        ["food.shop.list.store"] = "📍 {0}",
        ["food.shop.list.item"] = "  • {0}{1}{2}",
        ["food.shop.add.prompt"] = "Що додати до списку покупок? Напиши НАЗВУ АНГЛІЙСЬКОЮ (за бажанням також кількість і магазин, наприклад: \"Milk 2L Silpo\").",
        ["food.shop.clear.none"] = "Немає куплених товарів для очищення.",
        ["food.shop.clear.done"] = "Очищено куплених позицій: {0}.",
        ["food.shop.added"] = "Додано \"{0}\"{1}{2} до списку покупок.",
        ["food.weekly.view.empty"] = "Страв поки немає. Додай їх у Notion Meal Plans.",
        ["food.weekly.view.title"] = "Меню страв ({0}):",
        ["food.weekly.view.ingredients"] = "  Інгредієнти: {0}{1}",
        ["food.weekly.cookable.empty"] = "Зараз немає страв, які можна приготувати з поточних запасів. Спробуй синхронізацію з Notion або додай товари в запаси.",
        ["food.weekly.cookable.title"] = "Можна приготувати зараз ({0}):",
        ["food.weekly.calories.empty"] = "За останні 7 днів даних по калоріях немає.",
        ["food.weekly.calories.title"] = "📊 Калорії за останні 7 днів ({0} – {1})",
        ["food.weekly.calories.total"] = "Усього:  {0} ккал",
        ["food.weekly.calories.avg"] = "Середнє: {0:F0} ккал/день",
        ["food.weekly.calories.protein"] = "Білки: {0:F0} г",
        ["food.weekly.calories.carbs"] = "Вуглеводи: {0:F0} г",
        ["food.weekly.calories.fat"] = "Жири: {0:F0} г",
        ["food.weekly.favourites.empty"] = "Історії прийомів їжі поки немає. Записуй страви, щоб сформувати улюблені.",
        ["food.weekly.favourites.title"] = "⭐ Твої топ-страви ({0}):",
        ["food.weekly.log.empty"] = "Страв немає. Додай їх у Notion Meal Plans, а потім синхронізуй.",
        ["food.weekly.log.prompt"] = "Яку страву ти їв? Відповідь: ID страви та (за бажанням) кількість порцій:\n  Формат: <id>  або  <id> <порцій>  (наприклад: \"5\" або \"5 2.5\")",
        ["food.weekly.create.prompt"] = "Як назвемо страву? Напиши назву (наприклад: «Курка каррі» або «Паста карбонара»).",
        ["food.weekly.goal.title"] = "🎯 Прогрес на сьогодні — {0}",
        ["food.weekly.goal.consumed"] = "Спожито: {0} / {1} ккал",
        ["food.weekly.goal.remaining"] = "Залишилось: {0} ккал",
        ["food.weekly.goal.meals"] = "Прийомів їжі: {0}",
        ["food.weekly.diversity.empty"] = "За останні 7 днів страв не записано.",
        ["food.weekly.diversity.title"] = "🥗 Різноманітність раціону — за {0} днів",
        ["food.weekly.diversity.total"] = "Усього прийомів: {0}",
        ["food.weekly.diversity.unique"] = "Унікальних страв: {0}",
        ["food.weekly.diversity.repeated"] = "Найчастіше:",
        ["food.weekly.diversity.score"] = "Різноманітність: {0:F0}% унікальних",
        ["food.unknown"] = "Скористайся кнопками для розділів Запаси або Меню на тиждень.",
        ["stub.wip"] = "🚧 Ця функція в розробці. Скоро буде!",
        ["start.welcome"] = "👋 Привіт! Я Lagertha — твій особистий асистент.\n\nЯ вмію:\n📚 Вивчати англійські слова\n🛒 Вести список покупок\n🍽 Планувати меню на тиждень\n🗣 Просто розмовляти та допомагати\n\nОбери розділ або просто напиши мені!",
        ["locale.switched"] = "🌐 Мову змінено на українську",
        ["vocab.add.prompt"] = "Надішли слово або фразу англійською, і я знайду її для тебе.",
        ["vocab.import.choose_source"] = "Обери джерело імпорту:",
        ["vocab.import.source.photo"] = "🖼 Фото",
        ["vocab.import.source.file"] = "📄 Файл",
        ["vocab.import.source.url"] = "🔗 Посилання",
        ["vocab.import.source.text"] = "📝 Текст",
        ["vocab.import.prompt.photo"] = "Надішли фото з англійським текстом, і я витягну слова.",
        ["vocab.import.prompt.file"] = "Надішли файл (.txt, .md, .csv, .log, .json, .pdf, .xlsx, .xls, .xlsm), і я витягну слова.",
        ["vocab.import.prompt.url"] = "Надішли посилання на статтю, і я запропоную нові слова.",
        ["vocab.import.prompt.text"] = "Надішли текст, і я запропоную нові слова.",
        ["vocab.import.invalid_expected_photo"] = "⚠️ Очікую фото. Надішли фото або обери інше джерело.",
        ["vocab.import.invalid_expected_file"] = "⚠️ Очікую файл. Надішли підтримуваний файл або обери інше джерело.",
        ["vocab.import.invalid_expected_url"] = "⚠️ Очікую коректне посилання. Надішли URL, що починається з http:// або https://.",
        ["vocab.import.invalid_expected_text"] = "⚠️ Очікую звичайний текст. Встав текст або обери інше джерело.",
        ["vocab.import.file_unsupported"] = "⚠️ Тип файлу не підтримується. Підтримка: .txt, .md, .csv, .log, .json, .pdf, .xlsx, .xls, .xlsm.",
        ["vocab.import.photo_no_text"] = "ℹ️ Не вдалося витягти читабельний текст з фото.",
        ["vocab.import.file_no_text"] = "ℹ️ Не вдалося витягти читабельний текст із файлу.",
        ["vocab.import.read_failed"] = "⚠️ Імпорт не вдався: {0}",
        ["vocab.url.prompt"] = "Надішли URL статті або встав текст для імпорту, і я запропоную нові слова.",
        ["vocab.url.processing"] = "🔎 Аналізую джерело... Це може зайняти кілька секунд.",
        ["vocab.url.invalid"] = "⚠️ Не вдалося обробити джерело. Надішли коректне посилання або читабельний текст статті.",
        ["vocab.url.empty"] = "ℹ️ У цьому джерелі не знайдено нових іменників/дієслів/прикметників.",
        ["vocab.url.suggestions_title"] = "🔎 Рекомендовані нові слова: {0}",
        ["vocab.url.suggestions_group_n"] = "Іменники",
        ["vocab.url.suggestions_group_v"] = "Дієслова",
        ["vocab.url.suggestions_group_adj"] = "Прикметники",
        ["vocab.url.suggestions_hint"] = "❓Надішли номери слів для додавання (наприклад: 1,3,7). Або скористайся кнопками нижче.",
        ["vocab.url.select_parse_failed"] = "⚠️ Не вдалося розібрати вибір. Надішли номери у форматі 1,3,7 або скористайся кнопками.",
        ["vocab.url.selection_cancelled"] = "ℹ️ Імпорт скасовано.",
        ["vocab.url.no_pending"] = "Немає активного імпорту.",
        ["vocab.url.select_all"] = "✅ Додати всі рекомендовані слова",
        ["vocab.url.cancel"] = "❌ Скасувати імпорт",
        ["vocab.batch.prompt"] = "Надішли кілька слів або фраз одним повідомленням (новими рядками, комами, крапкою з комою або реченнями), і я оброблю їх у batch режимі.",
        ["vocab.stats.empty"] = "Індекс словника порожній. Додай слова, щоб побачити статистику.",
        ["vocab.stats.title"] = "📊 Статистика словника",
        ["vocab.stats.total"] = "Усього проіндексовано слів: {0}",
        ["vocab.stats.summary"] = "Файлів: {0} | Маркерів частин мови: {1}",
        ["vocab.stats.by_marker"] = "За частинами мови:",
        ["vocab.stats.top_decks"] = "Топ файлів:",
        ["vocab.stats.no_data"] = "• Поки що немає даних",
        ["vocab.stats.marker_unknown"] = "(без маркера)",
        ["vocab.stats.item"] = "• {0}: {1}",
        ["vocab.stats.deck_item"] = "{0}) {1} — {2}",
        ["vocab.stats.and_more_decks"] = "… і ще {0} файл(ів).",
        ["onboarding.choose_language"] = "👋 Вітаємо!\n\nБудь ласка, оберіть мову:",
        ["onboarding.language_saved"] = "🎉 Чудово! Мову збережено.\n\nПривіт! Я Lagertha — твій особистий асистент. Чим можу допомогти?",
        ["settings.title"] = "⚙️ <b>Налаштування</b>",
        ["settings.language"] = "🌐 Мова",
        ["settings.save_mode"] = "💾 Режим збереження",
        ["settings.ai"] = "🤖 AI",
        ["settings.storage_mode"] = "💽 Режим сховища",
        ["settings.onedrive"] = "☁️ OneDrive / Graph",
        ["settings.notion"] = "📝 Notion",
        ["settings.notion_enabled"] = "✅ Увімкнено",
        ["settings.notion_partial"] = "⚠️ Потрібне налаштування",
        ["settings.notion_disabled"] = "⏸ Вимкнено",
        ["settings.back"] = "🔙 Головне меню",
        ["settings.change_language"] = "🌐 Змінити мову",
        ["settings.change_save_mode"] = "💾 Змінити режим збереження",
        ["settings.change_ai"] = "🤖 Змінити AI",
        ["settings.change_storage_mode"] = "💽 Змінити режим сховища",
        ["ai.title"] = "🤖 <b>Налаштування AI</b>",
        ["ai.provider.label"] = "Провайдер",
        ["ai.model.label"] = "Модель",
        ["ai.key.label"] = "API ключ",
        ["ai.key.status.stored"] = "збережено в застосунку",
        ["ai.key.status.environment"] = "із змінних середовища",
        ["ai.key.status.missing"] = "не задано",
        ["ai.provider.change"] = "🔁 Змінити провайдера",
        ["ai.model.change"] = "🧠 Змінити модель",
        ["ai.key.set"] = "🔑 Встановити API ключ",
        ["ai.key.remove"] = "🗑 Видалити API ключ",
        ["ai.provider.title"] = "🔁 <b>Провайдер AI</b>\n\nПоточний: <b>{0}</b>\n\nОбери провайдера:",
        ["ai.provider.changed"] = "✅ Провайдера AI змінено на <b>{0}</b>.",
        ["ai.model.title"] = "🧠 <b>Модель AI</b>\n\nОбери модель для провайдера {0}:",
        ["ai.model.current"] = "Поточна",
        ["ai.model.changed"] = "✅ Модель AI змінено на <code>{0}</code>.",
        ["ai.key.prompt"] = "❓ Надішли API ключ для обраного провайдера.\n\nЩоб скасувати, введи <code>/cancel</code>.",
        ["ai.key.saved"] = "✅ API ключ для {0} збережено.",
        ["ai.key.removed"] = "✅ API ключ для {0} видалено.",
        ["ai.key.cancelled"] = "ℹ️ Оновлення API ключа скасовано.",
        ["ai.key.save_failed"] = "⚠️ Не вдалося зберегти API ключ. Спробуй ще раз.",
        ["language.current"] = "🌐 <b>Мова</b>\n\nПоточна: {0}\n\nОберіть нову мову:",
        ["language.changed"] = "✅ Мову змінено на {0}",
        ["savemode.title"] = "💾 <b>Режим збереження</b>\n\nПоточний: <b>{0}</b>\n\n• <b>auto</b> — зберігати автоматично\n• <b>ask</b> — підтверджувати перед збереженням\n• <b>off</b> — не зберігати в деку",
        ["savemode.changed"] = "✅ Режим збереження змінено на <b>{0}</b>",
        ["savemode.auto"] = "💾 auto",
        ["savemode.ask"] = "❓ ask",
        ["savemode.off"] = "🚫 off",
        ["storagemode.title"] = "💽 <b>Режим сховища</b>\n\nПоточний: <b>{0}</b>\n\n• <b>local</b> — збереження в локальні Excel-файли\n• <b>graph</b> — збереження в OneDrive через Microsoft Graph",
        ["storagemode.changed"] = "✅ Режим сховища змінено на <b>{0}</b>",
        ["storagemode.local"] = "💾 local",
        ["storagemode.graph"] = "☁️ graph",
        ["vocab.save.ask"] = "Зберегти \"{0}\" у \"{1}\"?",
        ["vocab.save.saved"] = "✅ Збережено в {0} (рядок {1}).",
        ["vocab.save.duplicate"] = "ℹ️ Слово вже є у writable-деках. Збереження пропущено.",
        ["vocab.save.skip"] = "ℹ️ Збереження пропущено.",
        ["vocab.save_failed"] = "⚠️ Помилка збереження: {0}",
        ["vocab.save_missing_deck"] = "⚠️ Save queued, but target deck file is missing in OneDrive: {0}. Add this file (or fix mapping), then run sync.",
        ["vocab.deck_unknown"] = "(unknown deck)",
        ["vocab.save_queued_waiting_auth"] = "⏳ Збережено в чергу. У файли OneDrive воно потрапить після авторизації (Налаштування -> OneDrive / Graph).",
        ["vocab.save_batch_ask_hint"] = "ℹ️ Режим збереження ask. Для batch-автозбереження перемкни на auto.",
        ["vocab.save_batch_ask_question"] = "Зберегти всі {0} нових елементів із цього batch?",
        ["vocab.save_batch_done"] = "✅ Batch-збереження завершено: збережено={0}, дублів={1}, помилок={2}.",
        ["vocab.save_batch_skip"] = "ℹ️ Batch-збереження пропущено.",
        ["vocab.save_mode_off_hint"] = "Режим збереження off. Перемкни в Settings на ask або auto.",
        ["vocab.save_yes"] = "✅ Зберегти",
        ["vocab.save_no"] = "❌ Пропустити",
        ["vocab.save_batch_yes"] = "✅ Зберегти все",
        ["vocab.save_batch_no"] = "❌ Пропустити все",
        ["vocab.no_pending_save"] = "Немає запиту на збереження.",
        ["vocab.word_unrecognized"] = "⚠️ Слово \"{0}\" не розпізнано. Надішли виправлений англійський варіант.",
        ["vocab.word_unrecognized_with_suggestions"] = "⚠️ Слово \"{0}\" не розпізнано. Можливо, ти мав на увазі: {1}? Надішли виправлене слово.",
        ["vocab.found_in_deck_single"] = "ℹ️ Слово вже є у словнику: {0} (рядок {1}).",
        ["vocab.found_in_deck_multi_title"] = "ℹ️ Ці слова вже є у словнику:",
        ["vocab.found_in_deck_multi_item"] = "• {0}: {1} (рядок {2})",
        ["vocab.graph_save_setup_required"] = "Щоб зберігати слова, відкрий Налаштування -> OneDrive / Graph, увійди і спробуй ще раз.",
        ["command.console_only_generic"] = "⚠️ Команда {0} доступна лише в консольному застосунку. У Telegram використовуй кнопки меню або природну мову.",
        ["command.console_only_graph"] = "⚠️ Команда {0} доступна лише в консолі. Щоб зберігати слова в Telegram, відкрий Налаштування -> OneDrive / Graph і увійди.",
        ["onedrive.login_switched_to_graph"] = "✅ OneDrive підключено. Режим сховища перемкнено на <b>graph</b>.",
        ["onedrive.title"] = "☁️ <b>OneDrive / Graph</b>",
        ["onedrive.status_connected"] = "Статус: ✅ Підключено",
        ["onedrive.status_disconnected"] = "Статус: ❌ Не підключено",
        ["onedrive.error_not_authenticated"] = "Потрібна авторизація OneDrive. Відкрий Налаштування -> OneDrive / Graph і увійди.",
        ["onedrive.error_expired"] = "Сесія OneDrive завершилась. Відкрий Налаштування -> OneDrive / Graph і увійди знову.",
        ["onedrive.error_not_configured"] = "Graph інтеграція не налаштована на сервері.",
        ["onedrive.error_timed_out"] = "Час входу вийшов. Спробуй ще раз у Налаштування -> OneDrive / Graph.",
        ["onedrive.error_declined"] = "Вхід було відхилено. Спробуй ще раз у Налаштування -> OneDrive / Graph.",
        ["onedrive.login"] = "🔑 Увійти в OneDrive",
        ["onedrive.logout"] = "🚪 Вийти",
        ["onedrive.login_started"] = "🔑 Щоб увійти, відкрий посилання та введи код:\n\n<b>{0}</b>\n\nПосилання: {1}\n\nКод діє {2} хвилин.",
        ["onedrive.logout_done"] = "✅ Вихід з OneDrive виконано.",
        ["onedrive.check_status"] = "✅ Я вже увійшов",
        ["onedrive.still_not_signed_in"] = "Ще не авторизовано. Спробувати ще раз?",
        ["onedrive.sync_now"] = "🔄 Синхронізувати чергу",
        ["onedrive.rebuild_index"] = "🧱 Перезібрати кеш",
        ["onedrive.rebuild_index_warning"] = "⚠️ Перезбір кешу може зайняти деякий час на великих деках. Запустити зараз?",
        ["onedrive.rebuild_index_start"] = "✅ Запустити перезбір",
        ["onedrive.rebuild_index_started"] = "⏳ Перезбираю кеш. Це може тривати кілька хвилин...",
        ["onedrive.rebuild_index_suggest"] = "💡 Порада: кеш виглядає порожнім. Натисни «Перезібрати кеш», щоб імпортувати наявні слова з OneDrive-дек.",
        ["onedrive.index_ready"] = "✅ Кеш уже в порядку: у словнику {0} слів.",
        ["onedrive.sync_now_done"] = "✅ Синхронізацію завершено: виконано={0}, повторно в чергу={1}, помилок={2}, в черзі={3}.",
        ["onedrive.rebuild_index_done"] = "✅ Кеш перезібрано з writable-дек: перевірено={0}, проіндексовано={1}.",
        ["onedrive.clear_cache"] = "🧹 Очистити кеш",
        ["onedrive.clear_cache_warning"] = "⚠️ Очистити кеш словника у базі? Записів для видалення: {0}. Файли OneDrive НЕ змінюються.",
        ["onedrive.clear_cache_start"] = "✅ Очистити кеш зараз",
        ["onedrive.clear_cache_done"] = "✅ Кеш очищено: видалено {0} запис(ів) з бази.",
        ["onedrive.clear_cache_hint"] = "💡 За потреби запусти «Перезібрати кеш», щоб знову імпортувати слова з writable-дек.",
        ["onedrive.decks_missing_title"] = "⚠️ У OneDrive бракує налаштованих цільових файлів ({0}):",
        ["onedrive.decks_missing_item"] = "• {0} → <code>{1}</code>",
        ["onedrive.decks_missing_hint"] = "⏳ Збереження для цих цілей лишається в черзі. Додай файли (або онови мапінг) і натисни «Синхронізувати чергу».",
        ["onedrive.operation_failed"] = "⚠️ Операція не вдалася: {0}",
        ["notion.title"] = "📝 <b>Notion</b>",
        ["notion.vocabulary"] = "Експорт словника",
        ["notion.food"] = "Синхронізація їжі",
        ["notion.status_enabled"] = "✅ Увімкнено",
        ["notion.status_disabled"] = "⏸ Вимкнено",
        ["notion.configured_yes"] = "✅ Налаштовано",
        ["notion.configured_no"] = "⚠️ Немає обов'язкових ключів",
        ["notion.worker_enabled"] = "✅ Воркер увімкнено",
        ["notion.worker_disabled"] = "⏸ Воркер вимкнено",
        ["notion.tip"] = "Щоб синхронізація працювала, додай Notion-ключі у Railway Variables.",
        ["back"] = "🔙 Назад",
        ["language.name.uk"] = "🇺🇦 Українська",
        ["language.name.en"] = "🇬🇧 English"
    };

    public string Get(string key, string locale)
    {
        var normalizedLocale = LocalizationConstants.NormalizeLocaleCode(locale);

        var dictionary = normalizedLocale switch
        {
            LocalizationConstants.UkrainianLocale => Ukrainian,
            _ => English
        };

        if (dictionary.TryGetValue(key, out var value))
        {
            return value;
        }

        if (English.TryGetValue(key, out var fallback))
        {
            if (!string.Equals(normalizedLocale, LocalizationConstants.EnglishLocale, StringComparison.Ordinal))
            {
                _logger?.LogDebug(
                    "Localization key '{Key}' missing for locale '{Locale}', using 'en' fallback.",
                    key,
                    normalizedLocale);
            }

            return fallback;
        }

        _logger?.LogWarning(
            "Localization key '{Key}' missing for all locales including 'en'. Returning placeholder.",
            key);
        return $"[?:{key}]";
    }

    public string GetLocaleForUser(string? telegramLanguageCode)
        => LocalizationConstants.NormalizeLocaleCode(telegramLanguageCode);
}


